#ifndef GUARD_CONSTANTS_PASSWORDS_H
#define GUARD_CONSTANTS_PASSWORDS_H

enum
{
    PASSWORD_ONE,
    PASSWORD_TWO,
    PASSWORD_THREE,
    PASSWORD_FOUR,
    PASSWORD_COUNT,
};

#endif //GUARD_CONSTANTS_PASSWORDS_H
