# 1 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"

# 2 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
DominionCity_MagaLab_SecurityHallway_MapScripts::
# 3 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.byte 0

DominionCity_MagaLab_SecurityHallway_MagaGrunt1::
# 7 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_1, DominionCity_MagaLab_SecurityHallway_MagaGrunt1_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt1_Text_1
# 11 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt1_Text_2
# 12 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_MagaGrunt2::
# 18 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_2, DominionCity_MagaLab_SecurityHallway_MagaGrunt2_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt2_Text_1
# 22 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt2_Text_2
# 23 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_MagaGrunt3::
# 29 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_3, DominionCity_MagaLab_SecurityHallway_MagaGrunt3_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt3_Text_1
# 33 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt3_Text_2
# 34 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_MagaGrunt4::
# 40 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_4, DominionCity_MagaLab_SecurityHallway_MagaGrunt4_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt4_Text_1
# 44 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt4_Text_2
# 45 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_MagaGrunt5::
# 51 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_5, DominionCity_MagaLab_SecurityHallway_MagaGrunt5_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt5_Text_1
# 55 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt5_Text_2
# 56 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_MagaGrunt6::
# 63 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_6, DominionCity_MagaLab_SecurityHallway_MagaGrunt6_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt6_Text_1
# 67 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt6_Text_2
# 68 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_MagaGrunt7::
# 75 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_7, DominionCity_MagaLab_SecurityHallway_MagaGrunt7_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt7_Text_1
# 79 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt7_Text_2
# 80 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_MagaGrunt8::
# 86 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_8, DominionCity_MagaLab_SecurityHallway_MagaGrunt8_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt8_Text_1
# 90 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt8_Text_2
# 91 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_MagaGrunt9::
# 97 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_9, DominionCity_MagaLab_SecurityHallway_MagaGrunt9_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt9_Text_1
# 101 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt9_Text_2
# 102 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_MagaGrunt10::
# 108 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SECURITY_HALLWAY_10, DominionCity_MagaLab_SecurityHallway_MagaGrunt10_Text_0, DominionCity_MagaLab_SecurityHallway_MagaGrunt10_Text_1
# 112 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_MagaGrunt10_Text_2
# 113 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	releaseall
	end


DominionCity_MagaLab_SecurityHallway_IntruderCaught::
# 119 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	msgbox DominionCity_MagaLab_SecurityHallway_IntruderCaught_Text_0
# 120 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	warpsilent MAP_DOMINION_CITY_MAGA_LAB_HOLDING_CELLS, 6, 3
	return


DominionCity_MagaLab_SecurityHallway_MagaGrunt1_Text_0:
# 8 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "What the-- how did you get out?! The\n"
	.string "cells were locked!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt1_Text_1:
# 9 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Tch, you're tougher than I thought…$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt1_Text_2:
# 11 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Stay right there! Security will take\n"
	.string "care of you!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt2_Text_0:
# 19 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Escaping, huh? Guess we'll see how far\n"
	.string "you get!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt2_Text_1:
# 20 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Ugh! You weren't supposed to win!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt2_Text_2:
# 22 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Doesn't matter. You won't make it past\n"
	.string "the last line of defense…$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt3_Text_0:
# 30 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "What kind of experiment are you,\n"
	.string "anyway?!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt3_Text_1:
# 31 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "No way… how is a test subject this\n"
	.string "strong?!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt3_Text_2:
# 33 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "They'll just send you back to the lab\n"
	.string "when you lose!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt4_Text_0:
# 41 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Hah! You think you can escape this\n"
	.string "place?$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt4_Text_1:
# 42 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "No way! I should've been stronger…$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt4_Text_2:
# 44 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Keep running, experiment. You'll hit a\n"
	.string "dead end soon enough.$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt5_Text_0:
# 52 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Hah! You're just a failed experiment.\n"
	.string "You won't last!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt5_Text_1:
# 53 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "What?! How did you beat me?!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt5_Text_2:
# 55 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Tch. Doesn't matter. The real\n"
	.string "experiment is waiting for you ahead…$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt6_Text_0:
# 64 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "There's no point fighting! You'll never\n"
	.string "get past security!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt6_Text_1:
# 65 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Grr… just a fluke!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt6_Text_2:
# 67 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Go ahead. Keep running. See what\n"
	.string "happens when you reach it…$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt7_Text_0:
# 76 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "An experiment like you shouldn't even\n"
	.string "be THINKING about escaping!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt7_Text_1:
# 77 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Ugh! What kind of mutation are you?!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt7_Text_2:
# 79 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "You're heading straight into a\n"
	.string "nightmare. The higher-ups made sure of\l"
	.string "that.$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt8_Text_0:
# 87 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "You're just a test subject! We OWN you!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt8_Text_1:
# 88 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "No… I was supposed to stop you!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt8_Text_2:
# 90 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "It's already waiting for you. I almost\n"
	.string "feel bad… Almost.$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt9_Text_0:
# 98 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Hah! You'll never get past our final\n"
	.string "security measure!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt9_Text_1:
# 99 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "How… how did you win?!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt9_Text_2:
# 101 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Doesn't matter. You're heading right\n"
	.string "into Porygon's domain.$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt10_Text_0:
# 109 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "You really don't get it, do you? This\n"
	.string "isn't just some lab…$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt10_Text_1:
# 110 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Tch. No way… I lost?!$"

DominionCity_MagaLab_SecurityHallway_MagaGrunt10_Text_2:
# 112 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "Heh. Hope you're ready, experiment. The\n"
	.string "real fight starts now…$"

DominionCity_MagaLab_SecurityHallway_IntruderCaught_Text_0:
# 119 "data/maps/DominionCity_MagaLab_SecurityHallway/scripts.pory"
	.string "What the-- how did you get out?! The\n"
	.string "cells were locked!\p"
	.string "Come with me, back to your cell!$"
