Emberglide_House2_MapScripts::
	.byte 0


EventScript_Emberglide_Diglett::
# 4 "data/maps/Emberglide_House2/scripts.pory"
	speakername EventScript_Emberglide_Diglett_Text_0
# 5 "data/maps/Emberglide_House2/scripts.pory"
	msgbox EventScript_Emberglide_Diglett_Text_1, MSGBOX_NPC
	return


EventScript_Emberglide_Diglett_Text_0:
# 4 "data/maps/Emberglide_House2/scripts.pory"
	.string "Diglett$"

EventScript_Emberglide_Diglett_Text_1:
# 6 "data/maps/Emberglide_House2/scripts.pory"
	.string "I am a tiny Diglett.\n"
	.string "But I have tall dreams.\p"
	.string "I wanna soar in the sky, one day.\p"
	.string "I've heard that there's a city high\n"
	.string "above the clouds, somewhere.\p"
	.string "If you find it, please tell me where it\n"
	.string "is.\p"
	.string "THIS IS A QUEST SETUP. THE QUEST IS NOT\n"
	.string "IMPLEMENTED YET.$"
