CommonEvents_PartyCommands_AddVeeToOverworldAtPlayersCoords::
	getplayerxy PlayerXCoordinates, PlayerYCoordinates
	setobjectxyperm LOCALID_VEE, PlayerXCoordinates, PlayerYCoordinates
	addobject LOCALID_VEE
    return

CommonEvents_PartyCommands_AddTalonToOverworldAtPlayersCoords::
	getplayerxy PlayerXCoordinates, PlayerYCoordinates
	setobjectxyperm LOCALID_TALON, PlayerXCoordinates, PlayerYCoordinates
	addobject LOCALID_TALON
    return

CommonEvents_PartyCommands_AddAceToOverworldAtPlayersCoords::
	getplayerxy PlayerXCoordinates, PlayerYCoordinates
	setobjectxyperm LOCALID_ACE, PlayerXCoordinates, PlayerYCoordinates
	addobject LOCALID_ACE
    return

CommonEvents_PartyCommands_AddNyxToOverworldAtPlayersCoords::
	getplayerxy PlayerXCoordinates, PlayerYCoordinates
	setobjectxyperm LOCALID_NYX, PlayerXCoordinates, PlayerYCoordinates
	addobject LOCALID_NYX
    return

CommonEvents_PartyCommands_AddDrakeToOverworldAtPlayersCoords::
	getplayerxy PlayerXCoordinates, PlayerYCoordinates
	setobjectxyperm LOCALID_DRAKE, PlayerXCoordinates, PlayerYCoordinates
	addobject LOCALID_DRAKE
    return
