Emberglide_House3_MapScripts::
	.byte 0


Emberglide_EventScript_Rhyhorn::
# 6 "data/maps/Emberglide_House3/scripts.pory"
	speakername Emberglide_EventScript_Rhyhorn_Text_0
# 7 "data/maps/Emberglide_House3/scripts.pory"
	msgbox Emberglide_EventScript_Rhyhorn_Text_1, MSGBOX_NPC
	end


Emberglide_EventScript_Rhyhorn_Text_0:
# 6 "data/maps/Emberglide_House3/scripts.pory"
	.string "Rhyhorn$"

Emberglide_EventScript_Rhyhorn_Text_1:
# 8 "data/maps/Emberglide_House3/scripts.pory"
	.string "What do I need a chair for?\n"
	.string "Simple.\p"
	.string "It's for my wife.$"
