#include "global.h"


#define INDEX_SPECIES_ODDISH 1
#define INDEX_SPECIES_GIRAFARIG 2
#define INDEX_SPECIES_NATU 3
#define INDEX_SPECIES_DODUO 4
#define INDEX_SPECIES_GLOOM 5
#define INDEX_SPECIES_WOBBUFFET 6
#define INDEX_SPECIES_PIKACHU 7
#define INDEX_SPECIES_COUNT 8

const u8 gAdditionalSpeciesData[] =
{
    [SPECIES_NONE] = 0,
#ifdef INDEX_SPECIES_BULBASAUR
    [SPECIES_BULBASAUR] = INDEX_SPECIES_BULBASAUR,
#else
    [SPECIES_BULBASAUR] = 0,
#endif
#ifdef INDEX_SPECIES_IVYSAUR
    [SPECIES_IVYSAUR] = INDEX_SPECIES_IVYSAUR,
#else
    [SPECIES_IVYSAUR] = 0,
#endif
#ifdef INDEX_SPECIES_VENUSAUR
    [SPECIES_VENUSAUR] = INDEX_SPECIES_VENUSAUR,
#else
    [SPECIES_VENUSAUR] = 0,
#endif
#ifdef INDEX_SPECIES_CHARMANDER
    [SPECIES_CHARMANDER] = INDEX_SPECIES_CHARMANDER,
#else
    [SPECIES_CHARMANDER] = 0,
#endif
#ifdef INDEX_SPECIES_CHARMELEON
    [SPECIES_CHARMELEON] = INDEX_SPECIES_CHARMELEON,
#else
    [SPECIES_CHARMELEON] = 0,
#endif
#ifdef INDEX_SPECIES_CHARIZARD
    [SPECIES_CHARIZARD] = INDEX_SPECIES_CHARIZARD,
#else
    [SPECIES_CHARIZARD] = 0,
#endif
#ifdef INDEX_SPECIES_SQUIRTLE
    [SPECIES_SQUIRTLE] = INDEX_SPECIES_SQUIRTLE,
#else
    [SPECIES_SQUIRTLE] = 0,
#endif
#ifdef INDEX_SPECIES_WARTORTLE
    [SPECIES_WARTORTLE] = INDEX_SPECIES_WARTORTLE,
#else
    [SPECIES_WARTORTLE] = 0,
#endif
#ifdef INDEX_SPECIES_BLASTOISE
    [SPECIES_BLASTOISE] = INDEX_SPECIES_BLASTOISE,
#else
    [SPECIES_BLASTOISE] = 0,
#endif
#ifdef INDEX_SPECIES_CATERPIE
    [SPECIES_CATERPIE] = INDEX_SPECIES_CATERPIE,
#else
    [SPECIES_CATERPIE] = 0,
#endif
#ifdef INDEX_SPECIES_METAPOD
    [SPECIES_METAPOD] = INDEX_SPECIES_METAPOD,
#else
    [SPECIES_METAPOD] = 0,
#endif
#ifdef INDEX_SPECIES_BUTTERFREE
    [SPECIES_BUTTERFREE] = INDEX_SPECIES_BUTTERFREE,
#else
    [SPECIES_BUTTERFREE] = 0,
#endif
#ifdef INDEX_SPECIES_WEEDLE
    [SPECIES_WEEDLE] = INDEX_SPECIES_WEEDLE,
#else
    [SPECIES_WEEDLE] = 0,
#endif
#ifdef INDEX_SPECIES_KAKUNA
    [SPECIES_KAKUNA] = INDEX_SPECIES_KAKUNA,
#else
    [SPECIES_KAKUNA] = 0,
#endif
#ifdef INDEX_SPECIES_BEEDRILL
    [SPECIES_BEEDRILL] = INDEX_SPECIES_BEEDRILL,
#else
    [SPECIES_BEEDRILL] = 0,
#endif
#ifdef INDEX_SPECIES_PIDGEY
    [SPECIES_PIDGEY] = INDEX_SPECIES_PIDGEY,
#else
    [SPECIES_PIDGEY] = 0,
#endif
#ifdef INDEX_SPECIES_PIDGEOTTO
    [SPECIES_PIDGEOTTO] = INDEX_SPECIES_PIDGEOTTO,
#else
    [SPECIES_PIDGEOTTO] = 0,
#endif
#ifdef INDEX_SPECIES_PIDGEOT
    [SPECIES_PIDGEOT] = INDEX_SPECIES_PIDGEOT,
#else
    [SPECIES_PIDGEOT] = 0,
#endif
#ifdef INDEX_SPECIES_RATTATA
    [SPECIES_RATTATA] = INDEX_SPECIES_RATTATA,
#else
    [SPECIES_RATTATA] = 0,
#endif
#ifdef INDEX_SPECIES_RATICATE
    [SPECIES_RATICATE] = INDEX_SPECIES_RATICATE,
#else
    [SPECIES_RATICATE] = 0,
#endif
#ifdef INDEX_SPECIES_SPEAROW
    [SPECIES_SPEAROW] = INDEX_SPECIES_SPEAROW,
#else
    [SPECIES_SPEAROW] = 0,
#endif
#ifdef INDEX_SPECIES_FEAROW
    [SPECIES_FEAROW] = INDEX_SPECIES_FEAROW,
#else
    [SPECIES_FEAROW] = 0,
#endif
#ifdef INDEX_SPECIES_EKANS
    [SPECIES_EKANS] = INDEX_SPECIES_EKANS,
#else
    [SPECIES_EKANS] = 0,
#endif
#ifdef INDEX_SPECIES_ARBOK
    [SPECIES_ARBOK] = INDEX_SPECIES_ARBOK,
#else
    [SPECIES_ARBOK] = 0,
#endif
#ifdef INDEX_SPECIES_PIKACHU
    [SPECIES_PIKACHU] = INDEX_SPECIES_PIKACHU,
#else
    [SPECIES_PIKACHU] = 0,
#endif
#ifdef INDEX_SPECIES_RAICHU
    [SPECIES_RAICHU] = INDEX_SPECIES_RAICHU,
#else
    [SPECIES_RAICHU] = 0,
#endif
#ifdef INDEX_SPECIES_SANDSHREW
    [SPECIES_SANDSHREW] = INDEX_SPECIES_SANDSHREW,
#else
    [SPECIES_SANDSHREW] = 0,
#endif
#ifdef INDEX_SPECIES_SANDSLASH
    [SPECIES_SANDSLASH] = INDEX_SPECIES_SANDSLASH,
#else
    [SPECIES_SANDSLASH] = 0,
#endif
#ifdef INDEX_SPECIES_NIDORAN_F
    [SPECIES_NIDORAN_F] = INDEX_SPECIES_NIDORAN_F,
#else
    [SPECIES_NIDORAN_F] = 0,
#endif
#ifdef INDEX_SPECIES_NIDORINA
    [SPECIES_NIDORINA] = INDEX_SPECIES_NIDORINA,
#else
    [SPECIES_NIDORINA] = 0,
#endif
#ifdef INDEX_SPECIES_NIDOQUEEN
    [SPECIES_NIDOQUEEN] = INDEX_SPECIES_NIDOQUEEN,
#else
    [SPECIES_NIDOQUEEN] = 0,
#endif
#ifdef INDEX_SPECIES_NIDORAN_M
    [SPECIES_NIDORAN_M] = INDEX_SPECIES_NIDORAN_M,
#else
    [SPECIES_NIDORAN_M] = 0,
#endif
#ifdef INDEX_SPECIES_NIDORINO
    [SPECIES_NIDORINO] = INDEX_SPECIES_NIDORINO,
#else
    [SPECIES_NIDORINO] = 0,
#endif
#ifdef INDEX_SPECIES_NIDOKING
    [SPECIES_NIDOKING] = INDEX_SPECIES_NIDOKING,
#else
    [SPECIES_NIDOKING] = 0,
#endif
#ifdef INDEX_SPECIES_CLEFAIRY
    [SPECIES_CLEFAIRY] = INDEX_SPECIES_CLEFAIRY,
#else
    [SPECIES_CLEFAIRY] = 0,
#endif
#ifdef INDEX_SPECIES_CLEFABLE
    [SPECIES_CLEFABLE] = INDEX_SPECIES_CLEFABLE,
#else
    [SPECIES_CLEFABLE] = 0,
#endif
#ifdef INDEX_SPECIES_VULPIX
    [SPECIES_VULPIX] = INDEX_SPECIES_VULPIX,
#else
    [SPECIES_VULPIX] = 0,
#endif
#ifdef INDEX_SPECIES_NINETALES
    [SPECIES_NINETALES] = INDEX_SPECIES_NINETALES,
#else
    [SPECIES_NINETALES] = 0,
#endif
#ifdef INDEX_SPECIES_JIGGLYPUFF
    [SPECIES_JIGGLYPUFF] = INDEX_SPECIES_JIGGLYPUFF,
#else
    [SPECIES_JIGGLYPUFF] = 0,
#endif
#ifdef INDEX_SPECIES_WIGGLYTUFF
    [SPECIES_WIGGLYTUFF] = INDEX_SPECIES_WIGGLYTUFF,
#else
    [SPECIES_WIGGLYTUFF] = 0,
#endif
#ifdef INDEX_SPECIES_ZUBAT
    [SPECIES_ZUBAT] = INDEX_SPECIES_ZUBAT,
#else
    [SPECIES_ZUBAT] = 0,
#endif
#ifdef INDEX_SPECIES_GOLBAT
    [SPECIES_GOLBAT] = INDEX_SPECIES_GOLBAT,
#else
    [SPECIES_GOLBAT] = 0,
#endif
#ifdef INDEX_SPECIES_ODDISH
    [SPECIES_ODDISH] = INDEX_SPECIES_ODDISH,
#else
    [SPECIES_ODDISH] = 0,
#endif
#ifdef INDEX_SPECIES_GLOOM
    [SPECIES_GLOOM] = INDEX_SPECIES_GLOOM,
#else
    [SPECIES_GLOOM] = 0,
#endif
#ifdef INDEX_SPECIES_VILEPLUME
    [SPECIES_VILEPLUME] = INDEX_SPECIES_VILEPLUME,
#else
    [SPECIES_VILEPLUME] = 0,
#endif
#ifdef INDEX_SPECIES_PARAS
    [SPECIES_PARAS] = INDEX_SPECIES_PARAS,
#else
    [SPECIES_PARAS] = 0,
#endif
#ifdef INDEX_SPECIES_PARASECT
    [SPECIES_PARASECT] = INDEX_SPECIES_PARASECT,
#else
    [SPECIES_PARASECT] = 0,
#endif
#ifdef INDEX_SPECIES_VENONAT
    [SPECIES_VENONAT] = INDEX_SPECIES_VENONAT,
#else
    [SPECIES_VENONAT] = 0,
#endif
#ifdef INDEX_SPECIES_VENOMOTH
    [SPECIES_VENOMOTH] = INDEX_SPECIES_VENOMOTH,
#else
    [SPECIES_VENOMOTH] = 0,
#endif
#ifdef INDEX_SPECIES_DIGLETT
    [SPECIES_DIGLETT] = INDEX_SPECIES_DIGLETT,
#else
    [SPECIES_DIGLETT] = 0,
#endif
#ifdef INDEX_SPECIES_DUGTRIO
    [SPECIES_DUGTRIO] = INDEX_SPECIES_DUGTRIO,
#else
    [SPECIES_DUGTRIO] = 0,
#endif
#ifdef INDEX_SPECIES_MEOWTH
    [SPECIES_MEOWTH] = INDEX_SPECIES_MEOWTH,
#else
    [SPECIES_MEOWTH] = 0,
#endif
#ifdef INDEX_SPECIES_PERSIAN
    [SPECIES_PERSIAN] = INDEX_SPECIES_PERSIAN,
#else
    [SPECIES_PERSIAN] = 0,
#endif
#ifdef INDEX_SPECIES_PSYDUCK
    [SPECIES_PSYDUCK] = INDEX_SPECIES_PSYDUCK,
#else
    [SPECIES_PSYDUCK] = 0,
#endif
#ifdef INDEX_SPECIES_GOLDUCK
    [SPECIES_GOLDUCK] = INDEX_SPECIES_GOLDUCK,
#else
    [SPECIES_GOLDUCK] = 0,
#endif
#ifdef INDEX_SPECIES_MANKEY
    [SPECIES_MANKEY] = INDEX_SPECIES_MANKEY,
#else
    [SPECIES_MANKEY] = 0,
#endif
#ifdef INDEX_SPECIES_PRIMEAPE
    [SPECIES_PRIMEAPE] = INDEX_SPECIES_PRIMEAPE,
#else
    [SPECIES_PRIMEAPE] = 0,
#endif
#ifdef INDEX_SPECIES_GROWLITHE
    [SPECIES_GROWLITHE] = INDEX_SPECIES_GROWLITHE,
#else
    [SPECIES_GROWLITHE] = 0,
#endif
#ifdef INDEX_SPECIES_ARCANINE
    [SPECIES_ARCANINE] = INDEX_SPECIES_ARCANINE,
#else
    [SPECIES_ARCANINE] = 0,
#endif
#ifdef INDEX_SPECIES_POLIWAG
    [SPECIES_POLIWAG] = INDEX_SPECIES_POLIWAG,
#else
    [SPECIES_POLIWAG] = 0,
#endif
#ifdef INDEX_SPECIES_POLIWHIRL
    [SPECIES_POLIWHIRL] = INDEX_SPECIES_POLIWHIRL,
#else
    [SPECIES_POLIWHIRL] = 0,
#endif
#ifdef INDEX_SPECIES_POLIWRATH
    [SPECIES_POLIWRATH] = INDEX_SPECIES_POLIWRATH,
#else
    [SPECIES_POLIWRATH] = 0,
#endif
#ifdef INDEX_SPECIES_ABRA
    [SPECIES_ABRA] = INDEX_SPECIES_ABRA,
#else
    [SPECIES_ABRA] = 0,
#endif
#ifdef INDEX_SPECIES_KADABRA
    [SPECIES_KADABRA] = INDEX_SPECIES_KADABRA,
#else
    [SPECIES_KADABRA] = 0,
#endif
#ifdef INDEX_SPECIES_ALAKAZAM
    [SPECIES_ALAKAZAM] = INDEX_SPECIES_ALAKAZAM,
#else
    [SPECIES_ALAKAZAM] = 0,
#endif
#ifdef INDEX_SPECIES_MACHOP
    [SPECIES_MACHOP] = INDEX_SPECIES_MACHOP,
#else
    [SPECIES_MACHOP] = 0,
#endif
#ifdef INDEX_SPECIES_MACHOKE
    [SPECIES_MACHOKE] = INDEX_SPECIES_MACHOKE,
#else
    [SPECIES_MACHOKE] = 0,
#endif
#ifdef INDEX_SPECIES_MACHAMP
    [SPECIES_MACHAMP] = INDEX_SPECIES_MACHAMP,
#else
    [SPECIES_MACHAMP] = 0,
#endif
#ifdef INDEX_SPECIES_BELLSPROUT
    [SPECIES_BELLSPROUT] = INDEX_SPECIES_BELLSPROUT,
#else
    [SPECIES_BELLSPROUT] = 0,
#endif
#ifdef INDEX_SPECIES_WEEPINBELL
    [SPECIES_WEEPINBELL] = INDEX_SPECIES_WEEPINBELL,
#else
    [SPECIES_WEEPINBELL] = 0,
#endif
#ifdef INDEX_SPECIES_VICTREEBEL
    [SPECIES_VICTREEBEL] = INDEX_SPECIES_VICTREEBEL,
#else
    [SPECIES_VICTREEBEL] = 0,
#endif
#ifdef INDEX_SPECIES_TENTACOOL
    [SPECIES_TENTACOOL] = INDEX_SPECIES_TENTACOOL,
#else
    [SPECIES_TENTACOOL] = 0,
#endif
#ifdef INDEX_SPECIES_TENTACRUEL
    [SPECIES_TENTACRUEL] = INDEX_SPECIES_TENTACRUEL,
#else
    [SPECIES_TENTACRUEL] = 0,
#endif
#ifdef INDEX_SPECIES_GEODUDE
    [SPECIES_GEODUDE] = INDEX_SPECIES_GEODUDE,
#else
    [SPECIES_GEODUDE] = 0,
#endif
#ifdef INDEX_SPECIES_GRAVELER
    [SPECIES_GRAVELER] = INDEX_SPECIES_GRAVELER,
#else
    [SPECIES_GRAVELER] = 0,
#endif
#ifdef INDEX_SPECIES_GOLEM
    [SPECIES_GOLEM] = INDEX_SPECIES_GOLEM,
#else
    [SPECIES_GOLEM] = 0,
#endif
#ifdef INDEX_SPECIES_PONYTA
    [SPECIES_PONYTA] = INDEX_SPECIES_PONYTA,
#else
    [SPECIES_PONYTA] = 0,
#endif
#ifdef INDEX_SPECIES_RAPIDASH
    [SPECIES_RAPIDASH] = INDEX_SPECIES_RAPIDASH,
#else
    [SPECIES_RAPIDASH] = 0,
#endif
#ifdef INDEX_SPECIES_SLOWPOKE
    [SPECIES_SLOWPOKE] = INDEX_SPECIES_SLOWPOKE,
#else
    [SPECIES_SLOWPOKE] = 0,
#endif
#ifdef INDEX_SPECIES_SLOWBRO
    [SPECIES_SLOWBRO] = INDEX_SPECIES_SLOWBRO,
#else
    [SPECIES_SLOWBRO] = 0,
#endif
#ifdef INDEX_SPECIES_MAGNEMITE
    [SPECIES_MAGNEMITE] = INDEX_SPECIES_MAGNEMITE,
#else
    [SPECIES_MAGNEMITE] = 0,
#endif
#ifdef INDEX_SPECIES_MAGNETON
    [SPECIES_MAGNETON] = INDEX_SPECIES_MAGNETON,
#else
    [SPECIES_MAGNETON] = 0,
#endif
#ifdef INDEX_SPECIES_FARFETCHD
    [SPECIES_FARFETCHD] = INDEX_SPECIES_FARFETCHD,
#else
    [SPECIES_FARFETCHD] = 0,
#endif
#ifdef INDEX_SPECIES_DODUO
    [SPECIES_DODUO] = INDEX_SPECIES_DODUO,
#else
    [SPECIES_DODUO] = 0,
#endif
#ifdef INDEX_SPECIES_DODRIO
    [SPECIES_DODRIO] = INDEX_SPECIES_DODRIO,
#else
    [SPECIES_DODRIO] = 0,
#endif
#ifdef INDEX_SPECIES_SEEL
    [SPECIES_SEEL] = INDEX_SPECIES_SEEL,
#else
    [SPECIES_SEEL] = 0,
#endif
#ifdef INDEX_SPECIES_DEWGONG
    [SPECIES_DEWGONG] = INDEX_SPECIES_DEWGONG,
#else
    [SPECIES_DEWGONG] = 0,
#endif
#ifdef INDEX_SPECIES_GRIMER
    [SPECIES_GRIMER] = INDEX_SPECIES_GRIMER,
#else
    [SPECIES_GRIMER] = 0,
#endif
#ifdef INDEX_SPECIES_MUK
    [SPECIES_MUK] = INDEX_SPECIES_MUK,
#else
    [SPECIES_MUK] = 0,
#endif
#ifdef INDEX_SPECIES_SHELLDER
    [SPECIES_SHELLDER] = INDEX_SPECIES_SHELLDER,
#else
    [SPECIES_SHELLDER] = 0,
#endif
#ifdef INDEX_SPECIES_CLOYSTER
    [SPECIES_CLOYSTER] = INDEX_SPECIES_CLOYSTER,
#else
    [SPECIES_CLOYSTER] = 0,
#endif
#ifdef INDEX_SPECIES_GASTLY
    [SPECIES_GASTLY] = INDEX_SPECIES_GASTLY,
#else
    [SPECIES_GASTLY] = 0,
#endif
#ifdef INDEX_SPECIES_HAUNTER
    [SPECIES_HAUNTER] = INDEX_SPECIES_HAUNTER,
#else
    [SPECIES_HAUNTER] = 0,
#endif
#ifdef INDEX_SPECIES_GENGAR
    [SPECIES_GENGAR] = INDEX_SPECIES_GENGAR,
#else
    [SPECIES_GENGAR] = 0,
#endif
#ifdef INDEX_SPECIES_ONIX
    [SPECIES_ONIX] = INDEX_SPECIES_ONIX,
#else
    [SPECIES_ONIX] = 0,
#endif
#ifdef INDEX_SPECIES_DROWZEE
    [SPECIES_DROWZEE] = INDEX_SPECIES_DROWZEE,
#else
    [SPECIES_DROWZEE] = 0,
#endif
#ifdef INDEX_SPECIES_HYPNO
    [SPECIES_HYPNO] = INDEX_SPECIES_HYPNO,
#else
    [SPECIES_HYPNO] = 0,
#endif
#ifdef INDEX_SPECIES_KRABBY
    [SPECIES_KRABBY] = INDEX_SPECIES_KRABBY,
#else
    [SPECIES_KRABBY] = 0,
#endif
#ifdef INDEX_SPECIES_KINGLER
    [SPECIES_KINGLER] = INDEX_SPECIES_KINGLER,
#else
    [SPECIES_KINGLER] = 0,
#endif
#ifdef INDEX_SPECIES_VOLTORB
    [SPECIES_VOLTORB] = INDEX_SPECIES_VOLTORB,
#else
    [SPECIES_VOLTORB] = 0,
#endif
#ifdef INDEX_SPECIES_ELECTRODE
    [SPECIES_ELECTRODE] = INDEX_SPECIES_ELECTRODE,
#else
    [SPECIES_ELECTRODE] = 0,
#endif
#ifdef INDEX_SPECIES_EXEGGCUTE
    [SPECIES_EXEGGCUTE] = INDEX_SPECIES_EXEGGCUTE,
#else
    [SPECIES_EXEGGCUTE] = 0,
#endif
#ifdef INDEX_SPECIES_EXEGGUTOR
    [SPECIES_EXEGGUTOR] = INDEX_SPECIES_EXEGGUTOR,
#else
    [SPECIES_EXEGGUTOR] = 0,
#endif
#ifdef INDEX_SPECIES_CUBONE
    [SPECIES_CUBONE] = INDEX_SPECIES_CUBONE,
#else
    [SPECIES_CUBONE] = 0,
#endif
#ifdef INDEX_SPECIES_MAROWAK
    [SPECIES_MAROWAK] = INDEX_SPECIES_MAROWAK,
#else
    [SPECIES_MAROWAK] = 0,
#endif
#ifdef INDEX_SPECIES_HITMONLEE
    [SPECIES_HITMONLEE] = INDEX_SPECIES_HITMONLEE,
#else
    [SPECIES_HITMONLEE] = 0,
#endif
#ifdef INDEX_SPECIES_HITMONCHAN
    [SPECIES_HITMONCHAN] = INDEX_SPECIES_HITMONCHAN,
#else
    [SPECIES_HITMONCHAN] = 0,
#endif
#ifdef INDEX_SPECIES_LICKITUNG
    [SPECIES_LICKITUNG] = INDEX_SPECIES_LICKITUNG,
#else
    [SPECIES_LICKITUNG] = 0,
#endif
#ifdef INDEX_SPECIES_KOFFING
    [SPECIES_KOFFING] = INDEX_SPECIES_KOFFING,
#else
    [SPECIES_KOFFING] = 0,
#endif
#ifdef INDEX_SPECIES_WEEZING
    [SPECIES_WEEZING] = INDEX_SPECIES_WEEZING,
#else
    [SPECIES_WEEZING] = 0,
#endif
#ifdef INDEX_SPECIES_RHYHORN
    [SPECIES_RHYHORN] = INDEX_SPECIES_RHYHORN,
#else
    [SPECIES_RHYHORN] = 0,
#endif
#ifdef INDEX_SPECIES_RHYDON
    [SPECIES_RHYDON] = INDEX_SPECIES_RHYDON,
#else
    [SPECIES_RHYDON] = 0,
#endif
#ifdef INDEX_SPECIES_CHANSEY
    [SPECIES_CHANSEY] = INDEX_SPECIES_CHANSEY,
#else
    [SPECIES_CHANSEY] = 0,
#endif
#ifdef INDEX_SPECIES_TANGELA
    [SPECIES_TANGELA] = INDEX_SPECIES_TANGELA,
#else
    [SPECIES_TANGELA] = 0,
#endif
#ifdef INDEX_SPECIES_KANGASKHAN
    [SPECIES_KANGASKHAN] = INDEX_SPECIES_KANGASKHAN,
#else
    [SPECIES_KANGASKHAN] = 0,
#endif
#ifdef INDEX_SPECIES_HORSEA
    [SPECIES_HORSEA] = INDEX_SPECIES_HORSEA,
#else
    [SPECIES_HORSEA] = 0,
#endif
#ifdef INDEX_SPECIES_SEADRA
    [SPECIES_SEADRA] = INDEX_SPECIES_SEADRA,
#else
    [SPECIES_SEADRA] = 0,
#endif
#ifdef INDEX_SPECIES_GOLDEEN
    [SPECIES_GOLDEEN] = INDEX_SPECIES_GOLDEEN,
#else
    [SPECIES_GOLDEEN] = 0,
#endif
#ifdef INDEX_SPECIES_SEAKING
    [SPECIES_SEAKING] = INDEX_SPECIES_SEAKING,
#else
    [SPECIES_SEAKING] = 0,
#endif
#ifdef INDEX_SPECIES_STARYU
    [SPECIES_STARYU] = INDEX_SPECIES_STARYU,
#else
    [SPECIES_STARYU] = 0,
#endif
#ifdef INDEX_SPECIES_STARMIE
    [SPECIES_STARMIE] = INDEX_SPECIES_STARMIE,
#else
    [SPECIES_STARMIE] = 0,
#endif
#ifdef INDEX_SPECIES_MR_MIME
    [SPECIES_MR_MIME] = INDEX_SPECIES_MR_MIME,
#else
    [SPECIES_MR_MIME] = 0,
#endif
#ifdef INDEX_SPECIES_SCYTHER
    [SPECIES_SCYTHER] = INDEX_SPECIES_SCYTHER,
#else
    [SPECIES_SCYTHER] = 0,
#endif
#ifdef INDEX_SPECIES_JYNX
    [SPECIES_JYNX] = INDEX_SPECIES_JYNX,
#else
    [SPECIES_JYNX] = 0,
#endif
#ifdef INDEX_SPECIES_ELECTABUZZ
    [SPECIES_ELECTABUZZ] = INDEX_SPECIES_ELECTABUZZ,
#else
    [SPECIES_ELECTABUZZ] = 0,
#endif
#ifdef INDEX_SPECIES_MAGMAR
    [SPECIES_MAGMAR] = INDEX_SPECIES_MAGMAR,
#else
    [SPECIES_MAGMAR] = 0,
#endif
#ifdef INDEX_SPECIES_PINSIR
    [SPECIES_PINSIR] = INDEX_SPECIES_PINSIR,
#else
    [SPECIES_PINSIR] = 0,
#endif
#ifdef INDEX_SPECIES_TAUROS
    [SPECIES_TAUROS] = INDEX_SPECIES_TAUROS,
#else
    [SPECIES_TAUROS] = 0,
#endif
#ifdef INDEX_SPECIES_MAGIKARP
    [SPECIES_MAGIKARP] = INDEX_SPECIES_MAGIKARP,
#else
    [SPECIES_MAGIKARP] = 0,
#endif
#ifdef INDEX_SPECIES_GYARADOS
    [SPECIES_GYARADOS] = INDEX_SPECIES_GYARADOS,
#else
    [SPECIES_GYARADOS] = 0,
#endif
#ifdef INDEX_SPECIES_LAPRAS
    [SPECIES_LAPRAS] = INDEX_SPECIES_LAPRAS,
#else
    [SPECIES_LAPRAS] = 0,
#endif
#ifdef INDEX_SPECIES_DITTO
    [SPECIES_DITTO] = INDEX_SPECIES_DITTO,
#else
    [SPECIES_DITTO] = 0,
#endif
#ifdef INDEX_SPECIES_EEVEE
    [SPECIES_EEVEE] = INDEX_SPECIES_EEVEE,
#else
    [SPECIES_EEVEE] = 0,
#endif
#ifdef INDEX_SPECIES_VAPOREON
    [SPECIES_VAPOREON] = INDEX_SPECIES_VAPOREON,
#else
    [SPECIES_VAPOREON] = 0,
#endif
#ifdef INDEX_SPECIES_JOLTEON
    [SPECIES_JOLTEON] = INDEX_SPECIES_JOLTEON,
#else
    [SPECIES_JOLTEON] = 0,
#endif
#ifdef INDEX_SPECIES_FLAREON
    [SPECIES_FLAREON] = INDEX_SPECIES_FLAREON,
#else
    [SPECIES_FLAREON] = 0,
#endif
#ifdef INDEX_SPECIES_PORYGON
    [SPECIES_PORYGON] = INDEX_SPECIES_PORYGON,
#else
    [SPECIES_PORYGON] = 0,
#endif
#ifdef INDEX_SPECIES_OMANYTE
    [SPECIES_OMANYTE] = INDEX_SPECIES_OMANYTE,
#else
    [SPECIES_OMANYTE] = 0,
#endif
#ifdef INDEX_SPECIES_OMASTAR
    [SPECIES_OMASTAR] = INDEX_SPECIES_OMASTAR,
#else
    [SPECIES_OMASTAR] = 0,
#endif
#ifdef INDEX_SPECIES_KABUTO
    [SPECIES_KABUTO] = INDEX_SPECIES_KABUTO,
#else
    [SPECIES_KABUTO] = 0,
#endif
#ifdef INDEX_SPECIES_KABUTOPS
    [SPECIES_KABUTOPS] = INDEX_SPECIES_KABUTOPS,
#else
    [SPECIES_KABUTOPS] = 0,
#endif
#ifdef INDEX_SPECIES_AERODACTYL
    [SPECIES_AERODACTYL] = INDEX_SPECIES_AERODACTYL,
#else
    [SPECIES_AERODACTYL] = 0,
#endif
#ifdef INDEX_SPECIES_SNORLAX
    [SPECIES_SNORLAX] = INDEX_SPECIES_SNORLAX,
#else
    [SPECIES_SNORLAX] = 0,
#endif
#ifdef INDEX_SPECIES_ARTICUNO
    [SPECIES_ARTICUNO] = INDEX_SPECIES_ARTICUNO,
#else
    [SPECIES_ARTICUNO] = 0,
#endif
#ifdef INDEX_SPECIES_ZAPDOS
    [SPECIES_ZAPDOS] = INDEX_SPECIES_ZAPDOS,
#else
    [SPECIES_ZAPDOS] = 0,
#endif
#ifdef INDEX_SPECIES_MOLTRES
    [SPECIES_MOLTRES] = INDEX_SPECIES_MOLTRES,
#else
    [SPECIES_MOLTRES] = 0,
#endif
#ifdef INDEX_SPECIES_DRATINI
    [SPECIES_DRATINI] = INDEX_SPECIES_DRATINI,
#else
    [SPECIES_DRATINI] = 0,
#endif
#ifdef INDEX_SPECIES_DRAGONAIR
    [SPECIES_DRAGONAIR] = INDEX_SPECIES_DRAGONAIR,
#else
    [SPECIES_DRAGONAIR] = 0,
#endif
#ifdef INDEX_SPECIES_DRAGONITE
    [SPECIES_DRAGONITE] = INDEX_SPECIES_DRAGONITE,
#else
    [SPECIES_DRAGONITE] = 0,
#endif
#ifdef INDEX_SPECIES_MEWTWO
    [SPECIES_MEWTWO] = INDEX_SPECIES_MEWTWO,
#else
    [SPECIES_MEWTWO] = 0,
#endif
#ifdef INDEX_SPECIES_MEW
    [SPECIES_MEW] = INDEX_SPECIES_MEW,
#else
    [SPECIES_MEW] = 0,
#endif
#ifdef INDEX_SPECIES_CHIKORITA
    [SPECIES_CHIKORITA] = INDEX_SPECIES_CHIKORITA,
#else
    [SPECIES_CHIKORITA] = 0,
#endif
#ifdef INDEX_SPECIES_BAYLEEF
    [SPECIES_BAYLEEF] = INDEX_SPECIES_BAYLEEF,
#else
    [SPECIES_BAYLEEF] = 0,
#endif
#ifdef INDEX_SPECIES_MEGANIUM
    [SPECIES_MEGANIUM] = INDEX_SPECIES_MEGANIUM,
#else
    [SPECIES_MEGANIUM] = 0,
#endif
#ifdef INDEX_SPECIES_CYNDAQUIL
    [SPECIES_CYNDAQUIL] = INDEX_SPECIES_CYNDAQUIL,
#else
    [SPECIES_CYNDAQUIL] = 0,
#endif
#ifdef INDEX_SPECIES_QUILAVA
    [SPECIES_QUILAVA] = INDEX_SPECIES_QUILAVA,
#else
    [SPECIES_QUILAVA] = 0,
#endif
#ifdef INDEX_SPECIES_TYPHLOSION
    [SPECIES_TYPHLOSION] = INDEX_SPECIES_TYPHLOSION,
#else
    [SPECIES_TYPHLOSION] = 0,
#endif
#ifdef INDEX_SPECIES_TOTODILE
    [SPECIES_TOTODILE] = INDEX_SPECIES_TOTODILE,
#else
    [SPECIES_TOTODILE] = 0,
#endif
#ifdef INDEX_SPECIES_CROCONAW
    [SPECIES_CROCONAW] = INDEX_SPECIES_CROCONAW,
#else
    [SPECIES_CROCONAW] = 0,
#endif
#ifdef INDEX_SPECIES_FERALIGATR
    [SPECIES_FERALIGATR] = INDEX_SPECIES_FERALIGATR,
#else
    [SPECIES_FERALIGATR] = 0,
#endif
#ifdef INDEX_SPECIES_SENTRET
    [SPECIES_SENTRET] = INDEX_SPECIES_SENTRET,
#else
    [SPECIES_SENTRET] = 0,
#endif
#ifdef INDEX_SPECIES_FURRET
    [SPECIES_FURRET] = INDEX_SPECIES_FURRET,
#else
    [SPECIES_FURRET] = 0,
#endif
#ifdef INDEX_SPECIES_HOOTHOOT
    [SPECIES_HOOTHOOT] = INDEX_SPECIES_HOOTHOOT,
#else
    [SPECIES_HOOTHOOT] = 0,
#endif
#ifdef INDEX_SPECIES_NOCTOWL
    [SPECIES_NOCTOWL] = INDEX_SPECIES_NOCTOWL,
#else
    [SPECIES_NOCTOWL] = 0,
#endif
#ifdef INDEX_SPECIES_LEDYBA
    [SPECIES_LEDYBA] = INDEX_SPECIES_LEDYBA,
#else
    [SPECIES_LEDYBA] = 0,
#endif
#ifdef INDEX_SPECIES_LEDIAN
    [SPECIES_LEDIAN] = INDEX_SPECIES_LEDIAN,
#else
    [SPECIES_LEDIAN] = 0,
#endif
#ifdef INDEX_SPECIES_SPINARAK
    [SPECIES_SPINARAK] = INDEX_SPECIES_SPINARAK,
#else
    [SPECIES_SPINARAK] = 0,
#endif
#ifdef INDEX_SPECIES_ARIADOS
    [SPECIES_ARIADOS] = INDEX_SPECIES_ARIADOS,
#else
    [SPECIES_ARIADOS] = 0,
#endif
#ifdef INDEX_SPECIES_CROBAT
    [SPECIES_CROBAT] = INDEX_SPECIES_CROBAT,
#else
    [SPECIES_CROBAT] = 0,
#endif
#ifdef INDEX_SPECIES_CHINCHOU
    [SPECIES_CHINCHOU] = INDEX_SPECIES_CHINCHOU,
#else
    [SPECIES_CHINCHOU] = 0,
#endif
#ifdef INDEX_SPECIES_LANTURN
    [SPECIES_LANTURN] = INDEX_SPECIES_LANTURN,
#else
    [SPECIES_LANTURN] = 0,
#endif
#ifdef INDEX_SPECIES_PICHU
    [SPECIES_PICHU] = INDEX_SPECIES_PICHU,
#else
    [SPECIES_PICHU] = 0,
#endif
#ifdef INDEX_SPECIES_CLEFFA
    [SPECIES_CLEFFA] = INDEX_SPECIES_CLEFFA,
#else
    [SPECIES_CLEFFA] = 0,
#endif
#ifdef INDEX_SPECIES_IGGLYBUFF
    [SPECIES_IGGLYBUFF] = INDEX_SPECIES_IGGLYBUFF,
#else
    [SPECIES_IGGLYBUFF] = 0,
#endif
#ifdef INDEX_SPECIES_TOGEPI
    [SPECIES_TOGEPI] = INDEX_SPECIES_TOGEPI,
#else
    [SPECIES_TOGEPI] = 0,
#endif
#ifdef INDEX_SPECIES_TOGETIC
    [SPECIES_TOGETIC] = INDEX_SPECIES_TOGETIC,
#else
    [SPECIES_TOGETIC] = 0,
#endif
#ifdef INDEX_SPECIES_NATU
    [SPECIES_NATU] = INDEX_SPECIES_NATU,
#else
    [SPECIES_NATU] = 0,
#endif
#ifdef INDEX_SPECIES_XATU
    [SPECIES_XATU] = INDEX_SPECIES_XATU,
#else
    [SPECIES_XATU] = 0,
#endif
#ifdef INDEX_SPECIES_MAREEP
    [SPECIES_MAREEP] = INDEX_SPECIES_MAREEP,
#else
    [SPECIES_MAREEP] = 0,
#endif
#ifdef INDEX_SPECIES_FLAAFFY
    [SPECIES_FLAAFFY] = INDEX_SPECIES_FLAAFFY,
#else
    [SPECIES_FLAAFFY] = 0,
#endif
#ifdef INDEX_SPECIES_AMPHAROS
    [SPECIES_AMPHAROS] = INDEX_SPECIES_AMPHAROS,
#else
    [SPECIES_AMPHAROS] = 0,
#endif
#ifdef INDEX_SPECIES_BELLOSSOM
    [SPECIES_BELLOSSOM] = INDEX_SPECIES_BELLOSSOM,
#else
    [SPECIES_BELLOSSOM] = 0,
#endif
#ifdef INDEX_SPECIES_MARILL
    [SPECIES_MARILL] = INDEX_SPECIES_MARILL,
#else
    [SPECIES_MARILL] = 0,
#endif
#ifdef INDEX_SPECIES_AZUMARILL
    [SPECIES_AZUMARILL] = INDEX_SPECIES_AZUMARILL,
#else
    [SPECIES_AZUMARILL] = 0,
#endif
#ifdef INDEX_SPECIES_SUDOWOODO
    [SPECIES_SUDOWOODO] = INDEX_SPECIES_SUDOWOODO,
#else
    [SPECIES_SUDOWOODO] = 0,
#endif
#ifdef INDEX_SPECIES_POLITOED
    [SPECIES_POLITOED] = INDEX_SPECIES_POLITOED,
#else
    [SPECIES_POLITOED] = 0,
#endif
#ifdef INDEX_SPECIES_HOPPIP
    [SPECIES_HOPPIP] = INDEX_SPECIES_HOPPIP,
#else
    [SPECIES_HOPPIP] = 0,
#endif
#ifdef INDEX_SPECIES_SKIPLOOM
    [SPECIES_SKIPLOOM] = INDEX_SPECIES_SKIPLOOM,
#else
    [SPECIES_SKIPLOOM] = 0,
#endif
#ifdef INDEX_SPECIES_JUMPLUFF
    [SPECIES_JUMPLUFF] = INDEX_SPECIES_JUMPLUFF,
#else
    [SPECIES_JUMPLUFF] = 0,
#endif
#ifdef INDEX_SPECIES_AIPOM
    [SPECIES_AIPOM] = INDEX_SPECIES_AIPOM,
#else
    [SPECIES_AIPOM] = 0,
#endif
#ifdef INDEX_SPECIES_SUNKERN
    [SPECIES_SUNKERN] = INDEX_SPECIES_SUNKERN,
#else
    [SPECIES_SUNKERN] = 0,
#endif
#ifdef INDEX_SPECIES_SUNFLORA
    [SPECIES_SUNFLORA] = INDEX_SPECIES_SUNFLORA,
#else
    [SPECIES_SUNFLORA] = 0,
#endif
#ifdef INDEX_SPECIES_YANMA
    [SPECIES_YANMA] = INDEX_SPECIES_YANMA,
#else
    [SPECIES_YANMA] = 0,
#endif
#ifdef INDEX_SPECIES_WOOPER
    [SPECIES_WOOPER] = INDEX_SPECIES_WOOPER,
#else
    [SPECIES_WOOPER] = 0,
#endif
#ifdef INDEX_SPECIES_QUAGSIRE
    [SPECIES_QUAGSIRE] = INDEX_SPECIES_QUAGSIRE,
#else
    [SPECIES_QUAGSIRE] = 0,
#endif
#ifdef INDEX_SPECIES_ESPEON
    [SPECIES_ESPEON] = INDEX_SPECIES_ESPEON,
#else
    [SPECIES_ESPEON] = 0,
#endif
#ifdef INDEX_SPECIES_UMBREON
    [SPECIES_UMBREON] = INDEX_SPECIES_UMBREON,
#else
    [SPECIES_UMBREON] = 0,
#endif
#ifdef INDEX_SPECIES_MURKROW
    [SPECIES_MURKROW] = INDEX_SPECIES_MURKROW,
#else
    [SPECIES_MURKROW] = 0,
#endif
#ifdef INDEX_SPECIES_SLOWKING
    [SPECIES_SLOWKING] = INDEX_SPECIES_SLOWKING,
#else
    [SPECIES_SLOWKING] = 0,
#endif
#ifdef INDEX_SPECIES_MISDREAVUS
    [SPECIES_MISDREAVUS] = INDEX_SPECIES_MISDREAVUS,
#else
    [SPECIES_MISDREAVUS] = 0,
#endif
#ifdef INDEX_SPECIES_UNOWN
    [SPECIES_UNOWN] = INDEX_SPECIES_UNOWN,
#else
    [SPECIES_UNOWN] = 0,
#endif
#ifdef INDEX_SPECIES_WOBBUFFET
    [SPECIES_WOBBUFFET] = INDEX_SPECIES_WOBBUFFET,
#else
    [SPECIES_WOBBUFFET] = 0,
#endif
#ifdef INDEX_SPECIES_GIRAFARIG
    [SPECIES_GIRAFARIG] = INDEX_SPECIES_GIRAFARIG,
#else
    [SPECIES_GIRAFARIG] = 0,
#endif
#ifdef INDEX_SPECIES_PINECO
    [SPECIES_PINECO] = INDEX_SPECIES_PINECO,
#else
    [SPECIES_PINECO] = 0,
#endif
#ifdef INDEX_SPECIES_FORRETRESS
    [SPECIES_FORRETRESS] = INDEX_SPECIES_FORRETRESS,
#else
    [SPECIES_FORRETRESS] = 0,
#endif
#ifdef INDEX_SPECIES_DUNSPARCE
    [SPECIES_DUNSPARCE] = INDEX_SPECIES_DUNSPARCE,
#else
    [SPECIES_DUNSPARCE] = 0,
#endif
#ifdef INDEX_SPECIES_GLIGAR
    [SPECIES_GLIGAR] = INDEX_SPECIES_GLIGAR,
#else
    [SPECIES_GLIGAR] = 0,
#endif
#ifdef INDEX_SPECIES_STEELIX
    [SPECIES_STEELIX] = INDEX_SPECIES_STEELIX,
#else
    [SPECIES_STEELIX] = 0,
#endif
#ifdef INDEX_SPECIES_SNUBBULL
    [SPECIES_SNUBBULL] = INDEX_SPECIES_SNUBBULL,
#else
    [SPECIES_SNUBBULL] = 0,
#endif
#ifdef INDEX_SPECIES_GRANBULL
    [SPECIES_GRANBULL] = INDEX_SPECIES_GRANBULL,
#else
    [SPECIES_GRANBULL] = 0,
#endif
#ifdef INDEX_SPECIES_QWILFISH
    [SPECIES_QWILFISH] = INDEX_SPECIES_QWILFISH,
#else
    [SPECIES_QWILFISH] = 0,
#endif
#ifdef INDEX_SPECIES_SCIZOR
    [SPECIES_SCIZOR] = INDEX_SPECIES_SCIZOR,
#else
    [SPECIES_SCIZOR] = 0,
#endif
#ifdef INDEX_SPECIES_SHUCKLE
    [SPECIES_SHUCKLE] = INDEX_SPECIES_SHUCKLE,
#else
    [SPECIES_SHUCKLE] = 0,
#endif
#ifdef INDEX_SPECIES_HERACROSS
    [SPECIES_HERACROSS] = INDEX_SPECIES_HERACROSS,
#else
    [SPECIES_HERACROSS] = 0,
#endif
#ifdef INDEX_SPECIES_SNEASEL
    [SPECIES_SNEASEL] = INDEX_SPECIES_SNEASEL,
#else
    [SPECIES_SNEASEL] = 0,
#endif
#ifdef INDEX_SPECIES_TEDDIURSA
    [SPECIES_TEDDIURSA] = INDEX_SPECIES_TEDDIURSA,
#else
    [SPECIES_TEDDIURSA] = 0,
#endif
#ifdef INDEX_SPECIES_URSARING
    [SPECIES_URSARING] = INDEX_SPECIES_URSARING,
#else
    [SPECIES_URSARING] = 0,
#endif
#ifdef INDEX_SPECIES_SLUGMA
    [SPECIES_SLUGMA] = INDEX_SPECIES_SLUGMA,
#else
    [SPECIES_SLUGMA] = 0,
#endif
#ifdef INDEX_SPECIES_MAGCARGO
    [SPECIES_MAGCARGO] = INDEX_SPECIES_MAGCARGO,
#else
    [SPECIES_MAGCARGO] = 0,
#endif
#ifdef INDEX_SPECIES_SWINUB
    [SPECIES_SWINUB] = INDEX_SPECIES_SWINUB,
#else
    [SPECIES_SWINUB] = 0,
#endif
#ifdef INDEX_SPECIES_PILOSWINE
    [SPECIES_PILOSWINE] = INDEX_SPECIES_PILOSWINE,
#else
    [SPECIES_PILOSWINE] = 0,
#endif
#ifdef INDEX_SPECIES_CORSOLA
    [SPECIES_CORSOLA] = INDEX_SPECIES_CORSOLA,
#else
    [SPECIES_CORSOLA] = 0,
#endif
#ifdef INDEX_SPECIES_REMORAID
    [SPECIES_REMORAID] = INDEX_SPECIES_REMORAID,
#else
    [SPECIES_REMORAID] = 0,
#endif
#ifdef INDEX_SPECIES_OCTILLERY
    [SPECIES_OCTILLERY] = INDEX_SPECIES_OCTILLERY,
#else
    [SPECIES_OCTILLERY] = 0,
#endif
#ifdef INDEX_SPECIES_DELIBIRD
    [SPECIES_DELIBIRD] = INDEX_SPECIES_DELIBIRD,
#else
    [SPECIES_DELIBIRD] = 0,
#endif
#ifdef INDEX_SPECIES_MANTINE
    [SPECIES_MANTINE] = INDEX_SPECIES_MANTINE,
#else
    [SPECIES_MANTINE] = 0,
#endif
#ifdef INDEX_SPECIES_SKARMORY
    [SPECIES_SKARMORY] = INDEX_SPECIES_SKARMORY,
#else
    [SPECIES_SKARMORY] = 0,
#endif
#ifdef INDEX_SPECIES_HOUNDOUR
    [SPECIES_HOUNDOUR] = INDEX_SPECIES_HOUNDOUR,
#else
    [SPECIES_HOUNDOUR] = 0,
#endif
#ifdef INDEX_SPECIES_HOUNDOOM
    [SPECIES_HOUNDOOM] = INDEX_SPECIES_HOUNDOOM,
#else
    [SPECIES_HOUNDOOM] = 0,
#endif
#ifdef INDEX_SPECIES_KINGDRA
    [SPECIES_KINGDRA] = INDEX_SPECIES_KINGDRA,
#else
    [SPECIES_KINGDRA] = 0,
#endif
#ifdef INDEX_SPECIES_PHANPY
    [SPECIES_PHANPY] = INDEX_SPECIES_PHANPY,
#else
    [SPECIES_PHANPY] = 0,
#endif
#ifdef INDEX_SPECIES_DONPHAN
    [SPECIES_DONPHAN] = INDEX_SPECIES_DONPHAN,
#else
    [SPECIES_DONPHAN] = 0,
#endif
#ifdef INDEX_SPECIES_PORYGON2
    [SPECIES_PORYGON2] = INDEX_SPECIES_PORYGON2,
#else
    [SPECIES_PORYGON2] = 0,
#endif
#ifdef INDEX_SPECIES_STANTLER
    [SPECIES_STANTLER] = INDEX_SPECIES_STANTLER,
#else
    [SPECIES_STANTLER] = 0,
#endif
#ifdef INDEX_SPECIES_SMEARGLE
    [SPECIES_SMEARGLE] = INDEX_SPECIES_SMEARGLE,
#else
    [SPECIES_SMEARGLE] = 0,
#endif
#ifdef INDEX_SPECIES_TYROGUE
    [SPECIES_TYROGUE] = INDEX_SPECIES_TYROGUE,
#else
    [SPECIES_TYROGUE] = 0,
#endif
#ifdef INDEX_SPECIES_HITMONTOP
    [SPECIES_HITMONTOP] = INDEX_SPECIES_HITMONTOP,
#else
    [SPECIES_HITMONTOP] = 0,
#endif
#ifdef INDEX_SPECIES_SMOOCHUM
    [SPECIES_SMOOCHUM] = INDEX_SPECIES_SMOOCHUM,
#else
    [SPECIES_SMOOCHUM] = 0,
#endif
#ifdef INDEX_SPECIES_ELEKID
    [SPECIES_ELEKID] = INDEX_SPECIES_ELEKID,
#else
    [SPECIES_ELEKID] = 0,
#endif
#ifdef INDEX_SPECIES_MAGBY
    [SPECIES_MAGBY] = INDEX_SPECIES_MAGBY,
#else
    [SPECIES_MAGBY] = 0,
#endif
#ifdef INDEX_SPECIES_MILTANK
    [SPECIES_MILTANK] = INDEX_SPECIES_MILTANK,
#else
    [SPECIES_MILTANK] = 0,
#endif
#ifdef INDEX_SPECIES_BLISSEY
    [SPECIES_BLISSEY] = INDEX_SPECIES_BLISSEY,
#else
    [SPECIES_BLISSEY] = 0,
#endif
#ifdef INDEX_SPECIES_RAIKOU
    [SPECIES_RAIKOU] = INDEX_SPECIES_RAIKOU,
#else
    [SPECIES_RAIKOU] = 0,
#endif
#ifdef INDEX_SPECIES_ENTEI
    [SPECIES_ENTEI] = INDEX_SPECIES_ENTEI,
#else
    [SPECIES_ENTEI] = 0,
#endif
#ifdef INDEX_SPECIES_SUICUNE
    [SPECIES_SUICUNE] = INDEX_SPECIES_SUICUNE,
#else
    [SPECIES_SUICUNE] = 0,
#endif
#ifdef INDEX_SPECIES_LARVITAR
    [SPECIES_LARVITAR] = INDEX_SPECIES_LARVITAR,
#else
    [SPECIES_LARVITAR] = 0,
#endif
#ifdef INDEX_SPECIES_PUPITAR
    [SPECIES_PUPITAR] = INDEX_SPECIES_PUPITAR,
#else
    [SPECIES_PUPITAR] = 0,
#endif
#ifdef INDEX_SPECIES_TYRANITAR
    [SPECIES_TYRANITAR] = INDEX_SPECIES_TYRANITAR,
#else
    [SPECIES_TYRANITAR] = 0,
#endif
#ifdef INDEX_SPECIES_LUGIA
    [SPECIES_LUGIA] = INDEX_SPECIES_LUGIA,
#else
    [SPECIES_LUGIA] = 0,
#endif
#ifdef INDEX_SPECIES_HO_OH
    [SPECIES_HO_OH] = INDEX_SPECIES_HO_OH,
#else
    [SPECIES_HO_OH] = 0,
#endif
#ifdef INDEX_SPECIES_CELEBI
    [SPECIES_CELEBI] = INDEX_SPECIES_CELEBI,
#else
    [SPECIES_CELEBI] = 0,
#endif
#ifdef INDEX_SPECIES_TREECKO
    [SPECIES_TREECKO] = INDEX_SPECIES_TREECKO,
#else
    [SPECIES_TREECKO] = 0,
#endif
#ifdef INDEX_SPECIES_GROVYLE
    [SPECIES_GROVYLE] = INDEX_SPECIES_GROVYLE,
#else
    [SPECIES_GROVYLE] = 0,
#endif
#ifdef INDEX_SPECIES_SCEPTILE
    [SPECIES_SCEPTILE] = INDEX_SPECIES_SCEPTILE,
#else
    [SPECIES_SCEPTILE] = 0,
#endif
#ifdef INDEX_SPECIES_TORCHIC
    [SPECIES_TORCHIC] = INDEX_SPECIES_TORCHIC,
#else
    [SPECIES_TORCHIC] = 0,
#endif
#ifdef INDEX_SPECIES_COMBUSKEN
    [SPECIES_COMBUSKEN] = INDEX_SPECIES_COMBUSKEN,
#else
    [SPECIES_COMBUSKEN] = 0,
#endif
#ifdef INDEX_SPECIES_BLAZIKEN
    [SPECIES_BLAZIKEN] = INDEX_SPECIES_BLAZIKEN,
#else
    [SPECIES_BLAZIKEN] = 0,
#endif
#ifdef INDEX_SPECIES_MUDKIP
    [SPECIES_MUDKIP] = INDEX_SPECIES_MUDKIP,
#else
    [SPECIES_MUDKIP] = 0,
#endif
#ifdef INDEX_SPECIES_MARSHTOMP
    [SPECIES_MARSHTOMP] = INDEX_SPECIES_MARSHTOMP,
#else
    [SPECIES_MARSHTOMP] = 0,
#endif
#ifdef INDEX_SPECIES_SWAMPERT
    [SPECIES_SWAMPERT] = INDEX_SPECIES_SWAMPERT,
#else
    [SPECIES_SWAMPERT] = 0,
#endif
#ifdef INDEX_SPECIES_POOCHYENA
    [SPECIES_POOCHYENA] = INDEX_SPECIES_POOCHYENA,
#else
    [SPECIES_POOCHYENA] = 0,
#endif
#ifdef INDEX_SPECIES_MIGHTYENA
    [SPECIES_MIGHTYENA] = INDEX_SPECIES_MIGHTYENA,
#else
    [SPECIES_MIGHTYENA] = 0,
#endif
#ifdef INDEX_SPECIES_ZIGZAGOON
    [SPECIES_ZIGZAGOON] = INDEX_SPECIES_ZIGZAGOON,
#else
    [SPECIES_ZIGZAGOON] = 0,
#endif
#ifdef INDEX_SPECIES_LINOONE
    [SPECIES_LINOONE] = INDEX_SPECIES_LINOONE,
#else
    [SPECIES_LINOONE] = 0,
#endif
#ifdef INDEX_SPECIES_WURMPLE
    [SPECIES_WURMPLE] = INDEX_SPECIES_WURMPLE,
#else
    [SPECIES_WURMPLE] = 0,
#endif
#ifdef INDEX_SPECIES_SILCOON
    [SPECIES_SILCOON] = INDEX_SPECIES_SILCOON,
#else
    [SPECIES_SILCOON] = 0,
#endif
#ifdef INDEX_SPECIES_BEAUTIFLY
    [SPECIES_BEAUTIFLY] = INDEX_SPECIES_BEAUTIFLY,
#else
    [SPECIES_BEAUTIFLY] = 0,
#endif
#ifdef INDEX_SPECIES_CASCOON
    [SPECIES_CASCOON] = INDEX_SPECIES_CASCOON,
#else
    [SPECIES_CASCOON] = 0,
#endif
#ifdef INDEX_SPECIES_DUSTOX
    [SPECIES_DUSTOX] = INDEX_SPECIES_DUSTOX,
#else
    [SPECIES_DUSTOX] = 0,
#endif
#ifdef INDEX_SPECIES_LOTAD
    [SPECIES_LOTAD] = INDEX_SPECIES_LOTAD,
#else
    [SPECIES_LOTAD] = 0,
#endif
#ifdef INDEX_SPECIES_LOMBRE
    [SPECIES_LOMBRE] = INDEX_SPECIES_LOMBRE,
#else
    [SPECIES_LOMBRE] = 0,
#endif
#ifdef INDEX_SPECIES_LUDICOLO
    [SPECIES_LUDICOLO] = INDEX_SPECIES_LUDICOLO,
#else
    [SPECIES_LUDICOLO] = 0,
#endif
#ifdef INDEX_SPECIES_SEEDOT
    [SPECIES_SEEDOT] = INDEX_SPECIES_SEEDOT,
#else
    [SPECIES_SEEDOT] = 0,
#endif
#ifdef INDEX_SPECIES_NUZLEAF
    [SPECIES_NUZLEAF] = INDEX_SPECIES_NUZLEAF,
#else
    [SPECIES_NUZLEAF] = 0,
#endif
#ifdef INDEX_SPECIES_SHIFTRY
    [SPECIES_SHIFTRY] = INDEX_SPECIES_SHIFTRY,
#else
    [SPECIES_SHIFTRY] = 0,
#endif
#ifdef INDEX_SPECIES_TAILLOW
    [SPECIES_TAILLOW] = INDEX_SPECIES_TAILLOW,
#else
    [SPECIES_TAILLOW] = 0,
#endif
#ifdef INDEX_SPECIES_SWELLOW
    [SPECIES_SWELLOW] = INDEX_SPECIES_SWELLOW,
#else
    [SPECIES_SWELLOW] = 0,
#endif
#ifdef INDEX_SPECIES_WINGULL
    [SPECIES_WINGULL] = INDEX_SPECIES_WINGULL,
#else
    [SPECIES_WINGULL] = 0,
#endif
#ifdef INDEX_SPECIES_PELIPPER
    [SPECIES_PELIPPER] = INDEX_SPECIES_PELIPPER,
#else
    [SPECIES_PELIPPER] = 0,
#endif
#ifdef INDEX_SPECIES_RALTS
    [SPECIES_RALTS] = INDEX_SPECIES_RALTS,
#else
    [SPECIES_RALTS] = 0,
#endif
#ifdef INDEX_SPECIES_KIRLIA
    [SPECIES_KIRLIA] = INDEX_SPECIES_KIRLIA,
#else
    [SPECIES_KIRLIA] = 0,
#endif
#ifdef INDEX_SPECIES_GARDEVOIR
    [SPECIES_GARDEVOIR] = INDEX_SPECIES_GARDEVOIR,
#else
    [SPECIES_GARDEVOIR] = 0,
#endif
#ifdef INDEX_SPECIES_SURSKIT
    [SPECIES_SURSKIT] = INDEX_SPECIES_SURSKIT,
#else
    [SPECIES_SURSKIT] = 0,
#endif
#ifdef INDEX_SPECIES_MASQUERAIN
    [SPECIES_MASQUERAIN] = INDEX_SPECIES_MASQUERAIN,
#else
    [SPECIES_MASQUERAIN] = 0,
#endif
#ifdef INDEX_SPECIES_SHROOMISH
    [SPECIES_SHROOMISH] = INDEX_SPECIES_SHROOMISH,
#else
    [SPECIES_SHROOMISH] = 0,
#endif
#ifdef INDEX_SPECIES_BRELOOM
    [SPECIES_BRELOOM] = INDEX_SPECIES_BRELOOM,
#else
    [SPECIES_BRELOOM] = 0,
#endif
#ifdef INDEX_SPECIES_SLAKOTH
    [SPECIES_SLAKOTH] = INDEX_SPECIES_SLAKOTH,
#else
    [SPECIES_SLAKOTH] = 0,
#endif
#ifdef INDEX_SPECIES_VIGOROTH
    [SPECIES_VIGOROTH] = INDEX_SPECIES_VIGOROTH,
#else
    [SPECIES_VIGOROTH] = 0,
#endif
#ifdef INDEX_SPECIES_SLAKING
    [SPECIES_SLAKING] = INDEX_SPECIES_SLAKING,
#else
    [SPECIES_SLAKING] = 0,
#endif
#ifdef INDEX_SPECIES_NINCADA
    [SPECIES_NINCADA] = INDEX_SPECIES_NINCADA,
#else
    [SPECIES_NINCADA] = 0,
#endif
#ifdef INDEX_SPECIES_NINJASK
    [SPECIES_NINJASK] = INDEX_SPECIES_NINJASK,
#else
    [SPECIES_NINJASK] = 0,
#endif
#ifdef INDEX_SPECIES_SHEDINJA
    [SPECIES_SHEDINJA] = INDEX_SPECIES_SHEDINJA,
#else
    [SPECIES_SHEDINJA] = 0,
#endif
#ifdef INDEX_SPECIES_WHISMUR
    [SPECIES_WHISMUR] = INDEX_SPECIES_WHISMUR,
#else
    [SPECIES_WHISMUR] = 0,
#endif
#ifdef INDEX_SPECIES_LOUDRED
    [SPECIES_LOUDRED] = INDEX_SPECIES_LOUDRED,
#else
    [SPECIES_LOUDRED] = 0,
#endif
#ifdef INDEX_SPECIES_EXPLOUD
    [SPECIES_EXPLOUD] = INDEX_SPECIES_EXPLOUD,
#else
    [SPECIES_EXPLOUD] = 0,
#endif
#ifdef INDEX_SPECIES_MAKUHITA
    [SPECIES_MAKUHITA] = INDEX_SPECIES_MAKUHITA,
#else
    [SPECIES_MAKUHITA] = 0,
#endif
#ifdef INDEX_SPECIES_HARIYAMA
    [SPECIES_HARIYAMA] = INDEX_SPECIES_HARIYAMA,
#else
    [SPECIES_HARIYAMA] = 0,
#endif
#ifdef INDEX_SPECIES_AZURILL
    [SPECIES_AZURILL] = INDEX_SPECIES_AZURILL,
#else
    [SPECIES_AZURILL] = 0,
#endif
#ifdef INDEX_SPECIES_NOSEPASS
    [SPECIES_NOSEPASS] = INDEX_SPECIES_NOSEPASS,
#else
    [SPECIES_NOSEPASS] = 0,
#endif
#ifdef INDEX_SPECIES_SKITTY
    [SPECIES_SKITTY] = INDEX_SPECIES_SKITTY,
#else
    [SPECIES_SKITTY] = 0,
#endif
#ifdef INDEX_SPECIES_DELCATTY
    [SPECIES_DELCATTY] = INDEX_SPECIES_DELCATTY,
#else
    [SPECIES_DELCATTY] = 0,
#endif
#ifdef INDEX_SPECIES_SABLEYE
    [SPECIES_SABLEYE] = INDEX_SPECIES_SABLEYE,
#else
    [SPECIES_SABLEYE] = 0,
#endif
#ifdef INDEX_SPECIES_MAWILE
    [SPECIES_MAWILE] = INDEX_SPECIES_MAWILE,
#else
    [SPECIES_MAWILE] = 0,
#endif
#ifdef INDEX_SPECIES_ARON
    [SPECIES_ARON] = INDEX_SPECIES_ARON,
#else
    [SPECIES_ARON] = 0,
#endif
#ifdef INDEX_SPECIES_LAIRON
    [SPECIES_LAIRON] = INDEX_SPECIES_LAIRON,
#else
    [SPECIES_LAIRON] = 0,
#endif
#ifdef INDEX_SPECIES_AGGRON
    [SPECIES_AGGRON] = INDEX_SPECIES_AGGRON,
#else
    [SPECIES_AGGRON] = 0,
#endif
#ifdef INDEX_SPECIES_MEDITITE
    [SPECIES_MEDITITE] = INDEX_SPECIES_MEDITITE,
#else
    [SPECIES_MEDITITE] = 0,
#endif
#ifdef INDEX_SPECIES_MEDICHAM
    [SPECIES_MEDICHAM] = INDEX_SPECIES_MEDICHAM,
#else
    [SPECIES_MEDICHAM] = 0,
#endif
#ifdef INDEX_SPECIES_ELECTRIKE
    [SPECIES_ELECTRIKE] = INDEX_SPECIES_ELECTRIKE,
#else
    [SPECIES_ELECTRIKE] = 0,
#endif
#ifdef INDEX_SPECIES_MANECTRIC
    [SPECIES_MANECTRIC] = INDEX_SPECIES_MANECTRIC,
#else
    [SPECIES_MANECTRIC] = 0,
#endif
#ifdef INDEX_SPECIES_PLUSLE
    [SPECIES_PLUSLE] = INDEX_SPECIES_PLUSLE,
#else
    [SPECIES_PLUSLE] = 0,
#endif
#ifdef INDEX_SPECIES_MINUN
    [SPECIES_MINUN] = INDEX_SPECIES_MINUN,
#else
    [SPECIES_MINUN] = 0,
#endif
#ifdef INDEX_SPECIES_VOLBEAT
    [SPECIES_VOLBEAT] = INDEX_SPECIES_VOLBEAT,
#else
    [SPECIES_VOLBEAT] = 0,
#endif
#ifdef INDEX_SPECIES_ILLUMISE
    [SPECIES_ILLUMISE] = INDEX_SPECIES_ILLUMISE,
#else
    [SPECIES_ILLUMISE] = 0,
#endif
#ifdef INDEX_SPECIES_ROSELIA
    [SPECIES_ROSELIA] = INDEX_SPECIES_ROSELIA,
#else
    [SPECIES_ROSELIA] = 0,
#endif
#ifdef INDEX_SPECIES_GULPIN
    [SPECIES_GULPIN] = INDEX_SPECIES_GULPIN,
#else
    [SPECIES_GULPIN] = 0,
#endif
#ifdef INDEX_SPECIES_SWALOT
    [SPECIES_SWALOT] = INDEX_SPECIES_SWALOT,
#else
    [SPECIES_SWALOT] = 0,
#endif
#ifdef INDEX_SPECIES_CARVANHA
    [SPECIES_CARVANHA] = INDEX_SPECIES_CARVANHA,
#else
    [SPECIES_CARVANHA] = 0,
#endif
#ifdef INDEX_SPECIES_SHARPEDO
    [SPECIES_SHARPEDO] = INDEX_SPECIES_SHARPEDO,
#else
    [SPECIES_SHARPEDO] = 0,
#endif
#ifdef INDEX_SPECIES_WAILMER
    [SPECIES_WAILMER] = INDEX_SPECIES_WAILMER,
#else
    [SPECIES_WAILMER] = 0,
#endif
#ifdef INDEX_SPECIES_WAILORD
    [SPECIES_WAILORD] = INDEX_SPECIES_WAILORD,
#else
    [SPECIES_WAILORD] = 0,
#endif
#ifdef INDEX_SPECIES_NUMEL
    [SPECIES_NUMEL] = INDEX_SPECIES_NUMEL,
#else
    [SPECIES_NUMEL] = 0,
#endif
#ifdef INDEX_SPECIES_CAMERUPT
    [SPECIES_CAMERUPT] = INDEX_SPECIES_CAMERUPT,
#else
    [SPECIES_CAMERUPT] = 0,
#endif
#ifdef INDEX_SPECIES_TORKOAL
    [SPECIES_TORKOAL] = INDEX_SPECIES_TORKOAL,
#else
    [SPECIES_TORKOAL] = 0,
#endif
#ifdef INDEX_SPECIES_SPOINK
    [SPECIES_SPOINK] = INDEX_SPECIES_SPOINK,
#else
    [SPECIES_SPOINK] = 0,
#endif
#ifdef INDEX_SPECIES_GRUMPIG
    [SPECIES_GRUMPIG] = INDEX_SPECIES_GRUMPIG,
#else
    [SPECIES_GRUMPIG] = 0,
#endif
#ifdef INDEX_SPECIES_SPINDA
    [SPECIES_SPINDA] = INDEX_SPECIES_SPINDA,
#else
    [SPECIES_SPINDA] = 0,
#endif
#ifdef INDEX_SPECIES_TRAPINCH
    [SPECIES_TRAPINCH] = INDEX_SPECIES_TRAPINCH,
#else
    [SPECIES_TRAPINCH] = 0,
#endif
#ifdef INDEX_SPECIES_VIBRAVA
    [SPECIES_VIBRAVA] = INDEX_SPECIES_VIBRAVA,
#else
    [SPECIES_VIBRAVA] = 0,
#endif
#ifdef INDEX_SPECIES_FLYGON
    [SPECIES_FLYGON] = INDEX_SPECIES_FLYGON,
#else
    [SPECIES_FLYGON] = 0,
#endif
#ifdef INDEX_SPECIES_CACNEA
    [SPECIES_CACNEA] = INDEX_SPECIES_CACNEA,
#else
    [SPECIES_CACNEA] = 0,
#endif
#ifdef INDEX_SPECIES_CACTURNE
    [SPECIES_CACTURNE] = INDEX_SPECIES_CACTURNE,
#else
    [SPECIES_CACTURNE] = 0,
#endif
#ifdef INDEX_SPECIES_SWABLU
    [SPECIES_SWABLU] = INDEX_SPECIES_SWABLU,
#else
    [SPECIES_SWABLU] = 0,
#endif
#ifdef INDEX_SPECIES_ALTARIA
    [SPECIES_ALTARIA] = INDEX_SPECIES_ALTARIA,
#else
    [SPECIES_ALTARIA] = 0,
#endif
#ifdef INDEX_SPECIES_ZANGOOSE
    [SPECIES_ZANGOOSE] = INDEX_SPECIES_ZANGOOSE,
#else
    [SPECIES_ZANGOOSE] = 0,
#endif
#ifdef INDEX_SPECIES_SEVIPER
    [SPECIES_SEVIPER] = INDEX_SPECIES_SEVIPER,
#else
    [SPECIES_SEVIPER] = 0,
#endif
#ifdef INDEX_SPECIES_LUNATONE
    [SPECIES_LUNATONE] = INDEX_SPECIES_LUNATONE,
#else
    [SPECIES_LUNATONE] = 0,
#endif
#ifdef INDEX_SPECIES_SOLROCK
    [SPECIES_SOLROCK] = INDEX_SPECIES_SOLROCK,
#else
    [SPECIES_SOLROCK] = 0,
#endif
#ifdef INDEX_SPECIES_BARBOACH
    [SPECIES_BARBOACH] = INDEX_SPECIES_BARBOACH,
#else
    [SPECIES_BARBOACH] = 0,
#endif
#ifdef INDEX_SPECIES_WHISCASH
    [SPECIES_WHISCASH] = INDEX_SPECIES_WHISCASH,
#else
    [SPECIES_WHISCASH] = 0,
#endif
#ifdef INDEX_SPECIES_CORPHISH
    [SPECIES_CORPHISH] = INDEX_SPECIES_CORPHISH,
#else
    [SPECIES_CORPHISH] = 0,
#endif
#ifdef INDEX_SPECIES_CRAWDAUNT
    [SPECIES_CRAWDAUNT] = INDEX_SPECIES_CRAWDAUNT,
#else
    [SPECIES_CRAWDAUNT] = 0,
#endif
#ifdef INDEX_SPECIES_BALTOY
    [SPECIES_BALTOY] = INDEX_SPECIES_BALTOY,
#else
    [SPECIES_BALTOY] = 0,
#endif
#ifdef INDEX_SPECIES_CLAYDOL
    [SPECIES_CLAYDOL] = INDEX_SPECIES_CLAYDOL,
#else
    [SPECIES_CLAYDOL] = 0,
#endif
#ifdef INDEX_SPECIES_LILEEP
    [SPECIES_LILEEP] = INDEX_SPECIES_LILEEP,
#else
    [SPECIES_LILEEP] = 0,
#endif
#ifdef INDEX_SPECIES_CRADILY
    [SPECIES_CRADILY] = INDEX_SPECIES_CRADILY,
#else
    [SPECIES_CRADILY] = 0,
#endif
#ifdef INDEX_SPECIES_ANORITH
    [SPECIES_ANORITH] = INDEX_SPECIES_ANORITH,
#else
    [SPECIES_ANORITH] = 0,
#endif
#ifdef INDEX_SPECIES_ARMALDO
    [SPECIES_ARMALDO] = INDEX_SPECIES_ARMALDO,
#else
    [SPECIES_ARMALDO] = 0,
#endif
#ifdef INDEX_SPECIES_FEEBAS
    [SPECIES_FEEBAS] = INDEX_SPECIES_FEEBAS,
#else
    [SPECIES_FEEBAS] = 0,
#endif
#ifdef INDEX_SPECIES_MILOTIC
    [SPECIES_MILOTIC] = INDEX_SPECIES_MILOTIC,
#else
    [SPECIES_MILOTIC] = 0,
#endif
#ifdef INDEX_SPECIES_CASTFORM
    [SPECIES_CASTFORM] = INDEX_SPECIES_CASTFORM,
#else
    [SPECIES_CASTFORM] = 0,
#endif
#ifdef INDEX_SPECIES_KECLEON
    [SPECIES_KECLEON] = INDEX_SPECIES_KECLEON,
#else
    [SPECIES_KECLEON] = 0,
#endif
#ifdef INDEX_SPECIES_SHUPPET
    [SPECIES_SHUPPET] = INDEX_SPECIES_SHUPPET,
#else
    [SPECIES_SHUPPET] = 0,
#endif
#ifdef INDEX_SPECIES_BANETTE
    [SPECIES_BANETTE] = INDEX_SPECIES_BANETTE,
#else
    [SPECIES_BANETTE] = 0,
#endif
#ifdef INDEX_SPECIES_DUSKULL
    [SPECIES_DUSKULL] = INDEX_SPECIES_DUSKULL,
#else
    [SPECIES_DUSKULL] = 0,
#endif
#ifdef INDEX_SPECIES_DUSCLOPS
    [SPECIES_DUSCLOPS] = INDEX_SPECIES_DUSCLOPS,
#else
    [SPECIES_DUSCLOPS] = 0,
#endif
#ifdef INDEX_SPECIES_TROPIUS
    [SPECIES_TROPIUS] = INDEX_SPECIES_TROPIUS,
#else
    [SPECIES_TROPIUS] = 0,
#endif
#ifdef INDEX_SPECIES_CHIMECHO
    [SPECIES_CHIMECHO] = INDEX_SPECIES_CHIMECHO,
#else
    [SPECIES_CHIMECHO] = 0,
#endif
#ifdef INDEX_SPECIES_ABSOL
    [SPECIES_ABSOL] = INDEX_SPECIES_ABSOL,
#else
    [SPECIES_ABSOL] = 0,
#endif
#ifdef INDEX_SPECIES_WYNAUT
    [SPECIES_WYNAUT] = INDEX_SPECIES_WYNAUT,
#else
    [SPECIES_WYNAUT] = 0,
#endif
#ifdef INDEX_SPECIES_SNORUNT
    [SPECIES_SNORUNT] = INDEX_SPECIES_SNORUNT,
#else
    [SPECIES_SNORUNT] = 0,
#endif
#ifdef INDEX_SPECIES_GLALIE
    [SPECIES_GLALIE] = INDEX_SPECIES_GLALIE,
#else
    [SPECIES_GLALIE] = 0,
#endif
#ifdef INDEX_SPECIES_SPHEAL
    [SPECIES_SPHEAL] = INDEX_SPECIES_SPHEAL,
#else
    [SPECIES_SPHEAL] = 0,
#endif
#ifdef INDEX_SPECIES_SEALEO
    [SPECIES_SEALEO] = INDEX_SPECIES_SEALEO,
#else
    [SPECIES_SEALEO] = 0,
#endif
#ifdef INDEX_SPECIES_WALREIN
    [SPECIES_WALREIN] = INDEX_SPECIES_WALREIN,
#else
    [SPECIES_WALREIN] = 0,
#endif
#ifdef INDEX_SPECIES_CLAMPERL
    [SPECIES_CLAMPERL] = INDEX_SPECIES_CLAMPERL,
#else
    [SPECIES_CLAMPERL] = 0,
#endif
#ifdef INDEX_SPECIES_HUNTAIL
    [SPECIES_HUNTAIL] = INDEX_SPECIES_HUNTAIL,
#else
    [SPECIES_HUNTAIL] = 0,
#endif
#ifdef INDEX_SPECIES_GOREBYSS
    [SPECIES_GOREBYSS] = INDEX_SPECIES_GOREBYSS,
#else
    [SPECIES_GOREBYSS] = 0,
#endif
#ifdef INDEX_SPECIES_RELICANTH
    [SPECIES_RELICANTH] = INDEX_SPECIES_RELICANTH,
#else
    [SPECIES_RELICANTH] = 0,
#endif
#ifdef INDEX_SPECIES_LUVDISC
    [SPECIES_LUVDISC] = INDEX_SPECIES_LUVDISC,
#else
    [SPECIES_LUVDISC] = 0,
#endif
#ifdef INDEX_SPECIES_BAGON
    [SPECIES_BAGON] = INDEX_SPECIES_BAGON,
#else
    [SPECIES_BAGON] = 0,
#endif
#ifdef INDEX_SPECIES_SHELGON
    [SPECIES_SHELGON] = INDEX_SPECIES_SHELGON,
#else
    [SPECIES_SHELGON] = 0,
#endif
#ifdef INDEX_SPECIES_SALAMENCE
    [SPECIES_SALAMENCE] = INDEX_SPECIES_SALAMENCE,
#else
    [SPECIES_SALAMENCE] = 0,
#endif
#ifdef INDEX_SPECIES_BELDUM
    [SPECIES_BELDUM] = INDEX_SPECIES_BELDUM,
#else
    [SPECIES_BELDUM] = 0,
#endif
#ifdef INDEX_SPECIES_METANG
    [SPECIES_METANG] = INDEX_SPECIES_METANG,
#else
    [SPECIES_METANG] = 0,
#endif
#ifdef INDEX_SPECIES_METAGROSS
    [SPECIES_METAGROSS] = INDEX_SPECIES_METAGROSS,
#else
    [SPECIES_METAGROSS] = 0,
#endif
#ifdef INDEX_SPECIES_REGIROCK
    [SPECIES_REGIROCK] = INDEX_SPECIES_REGIROCK,
#else
    [SPECIES_REGIROCK] = 0,
#endif
#ifdef INDEX_SPECIES_REGICE
    [SPECIES_REGICE] = INDEX_SPECIES_REGICE,
#else
    [SPECIES_REGICE] = 0,
#endif
#ifdef INDEX_SPECIES_REGISTEEL
    [SPECIES_REGISTEEL] = INDEX_SPECIES_REGISTEEL,
#else
    [SPECIES_REGISTEEL] = 0,
#endif
#ifdef INDEX_SPECIES_LATIAS
    [SPECIES_LATIAS] = INDEX_SPECIES_LATIAS,
#else
    [SPECIES_LATIAS] = 0,
#endif
#ifdef INDEX_SPECIES_LATIOS
    [SPECIES_LATIOS] = INDEX_SPECIES_LATIOS,
#else
    [SPECIES_LATIOS] = 0,
#endif
#ifdef INDEX_SPECIES_KYOGRE
    [SPECIES_KYOGRE] = INDEX_SPECIES_KYOGRE,
#else
    [SPECIES_KYOGRE] = 0,
#endif
#ifdef INDEX_SPECIES_GROUDON
    [SPECIES_GROUDON] = INDEX_SPECIES_GROUDON,
#else
    [SPECIES_GROUDON] = 0,
#endif
#ifdef INDEX_SPECIES_RAYQUAZA
    [SPECIES_RAYQUAZA] = INDEX_SPECIES_RAYQUAZA,
#else
    [SPECIES_RAYQUAZA] = 0,
#endif
#ifdef INDEX_SPECIES_JIRACHI
    [SPECIES_JIRACHI] = INDEX_SPECIES_JIRACHI,
#else
    [SPECIES_JIRACHI] = 0,
#endif
#ifdef INDEX_SPECIES_DEOXYS
    [SPECIES_DEOXYS] = INDEX_SPECIES_DEOXYS,
#else
    [SPECIES_DEOXYS] = 0,
#endif
};