#include "global.h"

#include "debug_scripting.h"

#ifdef DEBUG_SCRIPTING

#include "constants/map_scripts.h"

EWRAM_DATA u8 gActiveScriptDebugger = FALSE;

const u8 *const gBytecodeToString[] =
{
    [SCR_OP_NOP] = COMPOUND_STRING("nop"),
    [SCR_OP_NOP1] = COMPOUND_STRING("nop1"),
    [SCR_OP_END] = COMPOUND_STRING("end"),
    [SCR_OP_RETURN] = COMPOUND_STRING("return"),
    [SCR_OP_CALL] = COMPOUND_STRING("call"),
    [SCR_OP_GOTO] = COMPOUND_STRING("goto"),
    [SCR_OP_GOTO_IF] = COMPOUND_STRING("goto_if"),
    [SCR_OP_CALL_IF] = COMPOUND_STRING("call_if"),
    [SCR_OP_GOTO_STD] = COMPOUND_STRING("gotostd"),
    [SCR_OP_CALL_STD] = COMPOUND_STRING("callstd"),
    [SCR_OP_GOTO_STD_IF] = COMPOUND_STRING("gotostd_if"),
    [SCR_OP_CALL_STD_IF] = COMPOUND_STRING("callstd_if"),
    [SCR_OP_RETURNRAM] = COMPOUND_STRING("returnram"),
    [SCR_OP_ENDRAM] = COMPOUND_STRING("endram"),
    [SCR_OP_SETMYSTERYEVENTSTATUS] = COMPOUND_STRING("setmysteryeventstatus"),
    [SCR_OP_LOAD_WORD] = COMPOUND_STRING("loadword"),
    [SCR_OP_LOAD_BYTE] = COMPOUND_STRING("loadbyte"),
    [SCR_OP_SETPTR] = COMPOUND_STRING("setptr"),
    [SCR_OP_LOADBYTEFROMPTR] = COMPOUND_STRING("loadbytefromptr"),
    [SCR_OP_SETPTRBYTE] = COMPOUND_STRING("setptrbyte"),
    [SCR_OP_COPYLOCAL] = COMPOUND_STRING("copylocal"),
    [SCR_OP_COPYBYTE] = COMPOUND_STRING("copybyte"),
    [SCR_OP_SETVAR] = COMPOUND_STRING("setvar"),
    [SCR_OP_ADDVAR] = COMPOUND_STRING("addvar"),
    [SCR_OP_SUBVAR] = COMPOUND_STRING("subvar"),
    [SCR_OP_COPYVAR] = COMPOUND_STRING("copyvar"),
    [SCR_OP_SETORCOPYVAR] = COMPOUND_STRING("setorcopyvar"),
    [SCR_OP_COMPARE_LOCAL_TO_LOCAL] = COMPOUND_STRING("compare_local_to_local"),
    [SCR_OP_COMPARE_LOCAL_TO_VALUE] = COMPOUND_STRING("compare_local_to_value"),
    [SCR_OP_COMPARE_LOCAL_TO_PTR] = COMPOUND_STRING("compare_local_to_ptr"),
    [SCR_OP_COMPARE_PTR_TO_LOCAL] = COMPOUND_STRING("compare_ptr_to_local"),
    [SCR_OP_COMPARE_PTR_TO_VALUE] = COMPOUND_STRING("compare_ptr_to_value"),
    [SCR_OP_COMPARE_PTR_TO_PTR] = COMPOUND_STRING("compare_ptr_to_ptr"),
    [SCR_OP_COMPARE_VAR_TO_VALUE] = COMPOUND_STRING("compare_var_to_value"),
    [SCR_OP_COMPARE_VAR_TO_VAR] = COMPOUND_STRING("compare_var_to_var"),
    [SCR_OP_CALLNATIVE] = COMPOUND_STRING("callnative"),
    [SCR_OP_GOTONATIVE] = COMPOUND_STRING("gotonative"),
    [SCR_OP_SPECIAL] = COMPOUND_STRING("special"),
    [SCR_OP_SPECIALVAR] = COMPOUND_STRING("specialvar"),
    [SCR_OP_WAITSTATE] = COMPOUND_STRING("waitstate"),
    [SCR_OP_DELAY] = COMPOUND_STRING("delay"),
    [SCR_OP_SETFLAG] = COMPOUND_STRING("setflag"),
    [SCR_OP_CLEARFLAG] = COMPOUND_STRING("clearflag"),
    [SCR_OP_CHECKFLAG] = COMPOUND_STRING("checkflag"),
    [SCR_OP_INITCLOCK] = COMPOUND_STRING("initclock"),
    [SCR_OP_DOTIMEBASEDEVENTS] = COMPOUND_STRING("dotimebasedevents"),
    [SCR_OP_GETTIME] = COMPOUND_STRING("gettime"),
    [SCR_OP_PLAYSE] = COMPOUND_STRING("playse"),
    [SCR_OP_WAITSE] = COMPOUND_STRING("waitse"),
    [SCR_OP_PLAYFANFARE] = COMPOUND_STRING("playfanfare"),
    [SCR_OP_WAITFANFARE] = COMPOUND_STRING("waitfanfare"),
    [SCR_OP_PLAYBGM] = COMPOUND_STRING("playbgm"),
    [SCR_OP_SAVEBGM] = COMPOUND_STRING("savebgm"),
    [SCR_OP_FADEDEFAULTBGM] = COMPOUND_STRING("fadedefaultbgm"),
    [SCR_OP_FADENEWBGM] = COMPOUND_STRING("fadenewbgm"),
    [SCR_OP_FADEOUTBGM] = COMPOUND_STRING("fadeoutbgm"),
    [SCR_OP_FADEINBGM] = COMPOUND_STRING("fadeinbgm"),
    [SCR_OP_WARP] = COMPOUND_STRING("warp"),
    [SCR_OP_WARPSILENT] = COMPOUND_STRING("warpsilent"),
    [SCR_OP_WARPDOOR] = COMPOUND_STRING("warpdoor"),
    [SCR_OP_WARPHOLE] = COMPOUND_STRING("warphole"),
    [SCR_OP_WARPTELEPORT] = COMPOUND_STRING("warpteleport"),
    [SCR_OP_SETWARP] = COMPOUND_STRING("setwarp"),
    [SCR_OP_SETDYNAMICWARP] = COMPOUND_STRING("setdynamicwarp"),
    [SCR_OP_SETDIVEWARP] = COMPOUND_STRING("setdivewarp"),
    [SCR_OP_SETHOLEWARP] = COMPOUND_STRING("setholewarp"),
    [SCR_OP_GETPLAYERXY] = COMPOUND_STRING("getplayerxy"),
    [SCR_OP_GETPARTYSIZE] = COMPOUND_STRING("getpartysize"),
    [SCR_OP_ADDITEM] = COMPOUND_STRING("additem"),
    [SCR_OP_REMOVEITEM] = COMPOUND_STRING("removeitem"),
    [SCR_OP_CHECKITEMSPACE] = COMPOUND_STRING("checkitemspace"),
    [SCR_OP_CHECKITEM] = COMPOUND_STRING("checkitem"),
    [SCR_OP_CHECKITEMTYPE] = COMPOUND_STRING("checkitemtype"),
    [SCR_OP_ADDPCITEM] = COMPOUND_STRING("addpcitem"),
    [SCR_OP_CHECKPCITEM] = COMPOUND_STRING("checkpcitem"),
    [SCR_OP_ADDDECORATION] = COMPOUND_STRING("adddecoration"),
    [SCR_OP_REMOVEDECORATION] = COMPOUND_STRING("removedecoration"),
    [SCR_OP_CHECKDECOR] = COMPOUND_STRING("checkdecor"),
    [SCR_OP_CHECKDECORSPACE] = COMPOUND_STRING("checkdecorspace"),
    [SCR_OP_APPLYMOVEMENT] = COMPOUND_STRING("applymovement"),
    [SCR_OP_APPLYMOVEMENTAT] = COMPOUND_STRING("applymovementat"),
    [SCR_OP_WAITMOVEMENT] = COMPOUND_STRING("waitmovement"),
    [SCR_OP_WAITMOVEMENTAT] = COMPOUND_STRING("waitmovementat"),
    [SCR_OP_REMOVEOBJECT] = COMPOUND_STRING("removeobject"),
    [SCR_OP_REMOVEOBJECTAT] = COMPOUND_STRING("removeobjectat"),
    [SCR_OP_ADDOBJECT] = COMPOUND_STRING("addobject"),
    [SCR_OP_ADDOBJECTAT] = COMPOUND_STRING("addobjectat"),
    [SCR_OP_SETOBJECTXY] = COMPOUND_STRING("setobjectxy"),
    [SCR_OP_SHOWOBJECTAT] = COMPOUND_STRING("showobjectat"),
    [SCR_OP_HIDEOBJECTAT] = COMPOUND_STRING("hideobjectat"),
    [SCR_OP_FACEPLAYER] = COMPOUND_STRING("faceplayer"),
    [SCR_OP_TURNOBJECT] = COMPOUND_STRING("turnobject"),
    [SCR_OP_TRAINERBATTLE] = COMPOUND_STRING("trainerbattle"),
    [SCR_OP_DOTRAINERBATTLE] = COMPOUND_STRING("dotrainerbattle"),
    [SCR_OP_GOTOPOSTBATTLESCRIPT] = COMPOUND_STRING("gotopostbattlescript"),
    [SCR_OP_GOTOBEATENSCRIPT] = COMPOUND_STRING("gotobeatenscript"),
    [SCR_OP_CHECKTRAINERFLAG] = COMPOUND_STRING("checktrainerflag"),
    [SCR_OP_SETTRAINERFLAG] = COMPOUND_STRING("settrainerflag"),
    [SCR_OP_CLEARTRAINERFLAG] = COMPOUND_STRING("cleartrainerflag"),
    [SCR_OP_SETOBJECTXYPERM] = COMPOUND_STRING("setobjectxyperm"),
    [SCR_OP_COPYOBJECTXYTOPERM] = COMPOUND_STRING("copyobjectxytoperm"),
    [SCR_OP_SETOBJECTMOVEMENTTYPE] = COMPOUND_STRING("setobjectmovementtype"),
    [SCR_OP_WAITMESSAGE] = COMPOUND_STRING("waitmessage"),
    [SCR_OP_MESSAGE] = COMPOUND_STRING("message"),
    [SCR_OP_CLOSEMESSAGE] = COMPOUND_STRING("closemessage"),
    [SCR_OP_LOCKALL] = COMPOUND_STRING("lockall"),
    [SCR_OP_LOCK] = COMPOUND_STRING("lock"),
    [SCR_OP_RELEASEALL] = COMPOUND_STRING("releaseall"),
    [SCR_OP_RELEASE] = COMPOUND_STRING("release"),
    [SCR_OP_WAITBUTTONPRESS] = COMPOUND_STRING("waitbuttonpress"),
    [SCR_OP_YESNOBOX] = COMPOUND_STRING("yesnobox"),
    [SCR_OP_MULTICHOICE] = COMPOUND_STRING("multichoice"),
    [SCR_OP_MULTICHOICEDEFAULT] = COMPOUND_STRING("multichoicedefault"),
    [SCR_OP_MULTICHOICEGRID] = COMPOUND_STRING("multichoicegrid"),
    [SCR_OP_DRAWBOX] = COMPOUND_STRING("drawbox"),
    [SCR_OP_ERASEBOX] = COMPOUND_STRING("erasebox"),
    [SCR_OP_DRAWBOXTEXT] = COMPOUND_STRING("drawboxtext"),
    [SCR_OP_SHOWMONPIC] = COMPOUND_STRING("showmonpic"),
    [SCR_OP_HIDEMONPIC] = COMPOUND_STRING("hidemonpic"),
    [SCR_OP_SHOWCONTESTPAINTING] = COMPOUND_STRING("showcontestpainting"),
    [SCR_OP_BRAILLEMESSAGE] = COMPOUND_STRING("braillemessage"),
    [SCR_OP_GIVEMON] = COMPOUND_STRING("nop1"),
    [SCR_OP_GIVEEGG] = COMPOUND_STRING("giveegg"),
    [SCR_OP_SETMONMOVE] = COMPOUND_STRING("setmonmove"),
    [SCR_OP_CHECKFIELDMOVE] = COMPOUND_STRING("checkfieldmove"),
    [SCR_OP_BUFFERSPECIESNAME] = COMPOUND_STRING("bufferspeciesname"),
    [SCR_OP_BUFFERLEADMONSPECIESNAME] = COMPOUND_STRING("bufferleadmonspeciesname"),
    [SCR_OP_BUFFERPARTYMONNICK] = COMPOUND_STRING("bufferpartymonnick"),
    [SCR_OP_BUFFERITEMNAME] = COMPOUND_STRING("bufferitemname"),
    [SCR_OP_BUFFERDECORATIONNAME] = COMPOUND_STRING("bufferdecorationname"),
    [SCR_OP_BUFFERMOVENAME] = COMPOUND_STRING("buffermovename"),
    [SCR_OP_BUFFERNUMBERSTRING] = COMPOUND_STRING("buffernumberstring"),
    [SCR_OP_BUFFERSTDSTRING] = COMPOUND_STRING("bufferstdstring"),
    [SCR_OP_BUFFERSTRING] = COMPOUND_STRING("bufferstring"),
    [SCR_OP_POKEMART] = COMPOUND_STRING("pokemart"),
    [SCR_OP_POKEMARTDECORATION] = COMPOUND_STRING("pokemartdecoration"),
    [SCR_OP_POKEMARTDECORATION2] = COMPOUND_STRING("pokemartdecoration2"),
    [SCR_OP_PLAYSLOTMACHINE] = COMPOUND_STRING("playslotmachine"),
    [SCR_OP_SETBERRYTREE] = COMPOUND_STRING("setberrytree"),
    [SCR_OP_CHOOSECONTESTMON] = COMPOUND_STRING("choosecontestmon"),
    [SCR_OP_STARTCONTEST] = COMPOUND_STRING("startcontest"),
    [SCR_OP_SHOWCONTESTRESULTS] = COMPOUND_STRING("showcontestresults"),
    [SCR_OP_CONTESTLINKTRANSFER] = COMPOUND_STRING("contestlinktransfer"),
    [SCR_OP_RANDOM] = COMPOUND_STRING("random"),
    [SCR_OP_ADDMONEY] = COMPOUND_STRING("addmoney"),
    [SCR_OP_REMOVEMONEY] = COMPOUND_STRING("removemoney"),
    [SCR_OP_CHECKMONEY] = COMPOUND_STRING("checkmoney"),
    [SCR_OP_SHOWMONEYBOX] = COMPOUND_STRING("showmoneybox"),
    [SCR_OP_HIDEMONEYBOX] = COMPOUND_STRING("hidemoneybox"),
    [SCR_OP_UPDATEMONEYBOX] = COMPOUND_STRING("updatemoneybox"),
    [SCR_OP_GETPOKENEWSACTIVE] = COMPOUND_STRING("getpokenewsactive"),
    [SCR_OP_FADESCREEN] = COMPOUND_STRING("fadescreen"),
    [SCR_OP_FADESCREENSPEED] = COMPOUND_STRING("fadescreenspeed"),
    [SCR_OP_SETFLASHLEVEL] = COMPOUND_STRING("setflashlevel"),
    [SCR_OP_ANIMATEFLASH] = COMPOUND_STRING("animateflash"),
    [SCR_OP_MESSAGEAUTOSCROLL] = COMPOUND_STRING("messageautoscroll"),
    [SCR_OP_DOFIELDEFFECT] = COMPOUND_STRING("dofieldeffect"),
    [SCR_OP_SETFIELDEFFECTARGUMENT] = COMPOUND_STRING("setfieldeffectargument"),
    [SCR_OP_WAITFIELDEFFECT] = COMPOUND_STRING("waitfieldeffect"),
    [SCR_OP_SETRESPAWN] = COMPOUND_STRING("setrespawn"),
    [SCR_OP_CHECKPLAYERGENDER] = COMPOUND_STRING("checkplayergender"),
    [SCR_OP_PLAYMONCRY] = COMPOUND_STRING("playmoncry"),
    [SCR_OP_SETMETATILE] = COMPOUND_STRING("setmetatile"),
    [SCR_OP_RESETWEATHER] = COMPOUND_STRING("resetweather"),
    [SCR_OP_SETWEATHER] = COMPOUND_STRING("setweather"),
    [SCR_OP_DOWEATHER] = COMPOUND_STRING("doweather"),
    [SCR_OP_SETSTEPCALLBACK] = COMPOUND_STRING("setstepcallback"),
    [SCR_OP_SETMAPLAYOUTINDEX] = COMPOUND_STRING("setmaplayoutindex"),
    [SCR_OP_SETOBJECTSUBPRIORITY] = COMPOUND_STRING("setobjectsubpriority"),
    [SCR_OP_RESETOBJECTSUBPRIORITY] = COMPOUND_STRING("resetobjectsubpriority"),
    [SCR_OP_CREATEVOBJECT] = COMPOUND_STRING("createvobject"),
    [SCR_OP_TURNVOBJECT] = COMPOUND_STRING("turnvobject"),
    [SCR_OP_OPENDOOR] = COMPOUND_STRING("opendoor"),
    [SCR_OP_CLOSEDOOR] = COMPOUND_STRING("closedoor"),
    [SCR_OP_WAITDOORANIM] = COMPOUND_STRING("waitdooranim"),
    [SCR_OP_SETDOOROPEN] = COMPOUND_STRING("setdooropen"),
    [SCR_OP_SETDOORCLOSED] = COMPOUND_STRING("setdoorclosed"),
    [SCR_OP_ADDELEVMENUITEM] = COMPOUND_STRING("addelevmenuitem"),
    [SCR_OP_SHOWELEVMENU] = COMPOUND_STRING("showelevmenu"),
    [SCR_OP_CHECKCOINS] = COMPOUND_STRING("checkcoins"),
    [SCR_OP_ADDCOINS] = COMPOUND_STRING("addcoins"),
    [SCR_OP_REMOVECOINS] = COMPOUND_STRING("removecoins"),
    [SCR_OP_SETWILDBATTLE] = COMPOUND_STRING("setwildbattle"),
    [SCR_OP_DOWILDBATTLE] = COMPOUND_STRING("dowildbattle"),
    [SCR_OP_SETVADDRESS] = COMPOUND_STRING("setvaddress"),
    [SCR_OP_VGOTO] = COMPOUND_STRING("vgoto"),
    [SCR_OP_VCALL] = COMPOUND_STRING("vcall"),
    [SCR_OP_VGOTO_IF] = COMPOUND_STRING("vgoto_if"),
    [SCR_OP_VCALL_IF] = COMPOUND_STRING("vcall_if"),
    [SCR_OP_VMESSAGE] = COMPOUND_STRING("vmessage"),
    [SCR_OP_VBUFFERMESSAGE] = COMPOUND_STRING("vbuffermessage"),
    [SCR_OP_VBUFFERSTRING] = COMPOUND_STRING("vbufferstring"),
    [SCR_OP_SHOWCOINSBOX] = COMPOUND_STRING("showcoinsbox"),
    [SCR_OP_HIDECOINSBOX] = COMPOUND_STRING("hidecoinsbox"),
    [SCR_OP_UPDATECOINSBOX] = COMPOUND_STRING("updatecoinsbox"),
    [SCR_OP_INCREMENTGAMESTAT] = COMPOUND_STRING("incrementgamestat"),
    [SCR_OP_SETESCAPEWARP] = COMPOUND_STRING("setescapewarp"),
    [SCR_OP_WAITMONCRY] = COMPOUND_STRING("waitmoncry"),
    [SCR_OP_BUFFERBOXNAME] = COMPOUND_STRING("bufferboxname"),
    [SCR_OP_TEXTCOLOR] = COMPOUND_STRING("nop1"),
    [SCR_OP_LOADHELP] = COMPOUND_STRING("nop1"),
    [SCR_OP_UNLOADHELP] = COMPOUND_STRING("nop1"),
    [SCR_OP_SIGNMSG] = COMPOUND_STRING("nop1"),
    [SCR_OP_NORMALMSG] = COMPOUND_STRING("nop1"),
    [SCR_OP_COMPAREHIDDENVAR] = COMPOUND_STRING("nop1"),
    [SCR_OP_SETMODERNFATEFULENCOUNTER] = COMPOUND_STRING("setmodernfatefulencounter"),
    [SCR_OP_CHECKMODERNFATEFULENCOUNTER] = COMPOUND_STRING("checkmodernfatefulencounter"),
    [SCR_OP_TRYWONDERCARDSCRIPT] = COMPOUND_STRING("trywondercardscript"),
    [SCR_OP_SETWORLDMAPFLAG] = COMPOUND_STRING("nop1"),
    [SCR_OP_WARPSPINENTER] = COMPOUND_STRING("warpspinenter"),
    [SCR_OP_SETMONMETLOCATION] = COMPOUND_STRING("setmonmetlocation"),
    [SCR_OP_MOVEROTATINGTILEOBJECTS] = COMPOUND_STRING("moverotatingtileobjects"),
    [SCR_OP_TURNROTATINGTILEOBJECTS] = COMPOUND_STRING("turnrotatingtileobjects"),
    [SCR_OP_INITROTATINGTILEPUZZLE] = COMPOUND_STRING("initrotatingtilepuzzle"),
    [SCR_OP_FREEROTATINGTILEPUZZLE] = COMPOUND_STRING("freerotatingtilepuzzle"),
    [SCR_OP_WARPMOSSDEEPGYM] = COMPOUND_STRING("warpmossdeepgym"),
    [SCR_OP_SELECTAPPROACHINGTRAINER] = COMPOUND_STRING("selectapproachingtrainer"),
    [SCR_OP_LOCKFORTRAINER] = COMPOUND_STRING("lockfortrainer"),
    [SCR_OP_CLOSEBRAILLEMESSAGE] = COMPOUND_STRING("closebraillemessage"),
    [SCR_OP_MESSAGEINSTANT] = COMPOUND_STRING("messageinstant"),
    [SCR_OP_FADESCREENSWAPBUFFERS] = COMPOUND_STRING("fadescreenswapbuffers"),
    [SCR_OP_BUFFERTRAINERCLASSNAME] = COMPOUND_STRING("buffertrainerclassname"),
    [SCR_OP_BUFFERTRAINERNAME] = COMPOUND_STRING("buffertrainername"),
    [SCR_OP_POKENAVCALL] = COMPOUND_STRING("pokenavcall"),
    [SCR_OP_WARPWHITEFADE] = COMPOUND_STRING("warpwhitefade"),
    [SCR_OP_BUFFERCONTESTNAME] = COMPOUND_STRING("buffercontestname"),
    [SCR_OP_BUFFERITEMNAMEPLURAL] = COMPOUND_STRING("bufferitemnameplural"),
    [SCR_OP_DYNMULTICHOICE] = COMPOUND_STRING("dynmultichoice"),
    [SCR_OP_DYNMULTIPUSH] = COMPOUND_STRING("dynmultipush"),
};






const u8 *const gSpecialStrings[] =
{
    COMPOUND_STRING("HealPlayerParty"),
    COMPOUND_STRING("SetCableClubWarp"),
    COMPOUND_STRING("DoCableClubWarp"),
    COMPOUND_STRING("ReturnFromLinkRoom"),
    COMPOUND_STRING("CleanupLinkRoomState"),
    COMPOUND_STRING("ExitLinkRoom"),
    COMPOUND_STRING("SetPlayerSecretBase"),
    COMPOUND_STRING("CheckPlayerHasSecretBase"),
    COMPOUND_STRING("EnterSecretBase"),
    COMPOUND_STRING("ClearAndLeaveSecretBase"),
    COMPOUND_STRING("MoveOutOfSecretBase"),
    COMPOUND_STRING("IsCurSecretBaseOwnedByAnotherPlayer"),
    COMPOUND_STRING("GetCurSecretBaseRegistrationValidity"),
    COMPOUND_STRING("ToggleCurSecretBaseRegistry"),
    COMPOUND_STRING("ShowSecretBaseDecorationMenu"),
    COMPOUND_STRING("ShowSecretBaseRegistryMenu"),
    COMPOUND_STRING("PrepSecretBaseBattleFlags"),
    COMPOUND_STRING("GetSecretBaseOwnerAndState"),
    COMPOUND_STRING("InitSecretBaseDecorationSprites"),
    COMPOUND_STRING("SetDecoration"),
    COMPOUND_STRING("GetObjectEventLocalIdByFlag"),
    COMPOUND_STRING("GetSecretBaseTypeInFrontOfPlayer"),
    COMPOUND_STRING("SetSecretBaseOwnerGfxId"),
    COMPOUND_STRING("PutAwayDecorationIteration"),
    COMPOUND_STRING("EnterNewlyCreatedSecretBase"),
    COMPOUND_STRING("SetBattledOwnerFromResult"),
    COMPOUND_STRING("DoSecretBasePCTurnOffEffect"),
    COMPOUND_STRING("RecordMixingPlayerSpotTriggered"),
    COMPOUND_STRING("TryBattleLinkup"),
    COMPOUND_STRING("TryTradeLinkup"),
    COMPOUND_STRING("TryRecordMixLinkup"),
    COMPOUND_STRING("ValidateMixingGameLanguage"),
    COMPOUND_STRING("CloseLink"),
    COMPOUND_STRING("ColosseumPlayerSpotTriggered"),
    COMPOUND_STRING("PlayerEnteredTradeSeat"),
    COMPOUND_STRING("Script_StartWiredTrade"),
    COMPOUND_STRING("CableClubSaveGame"),
    COMPOUND_STRING("TryBerryBlenderLinkup"),
    COMPOUND_STRING("GetLinkPartnerNames"),
    COMPOUND_STRING("SpawnLinkPartnerObjectEvent"),
    COMPOUND_STRING("SavePlayerParty"),
    COMPOUND_STRING("LoadPlayerParty"),
    COMPOUND_STRING("ChooseHalfPartyForBattle"),
    COMPOUND_STRING("Script_ShowLinkTrainerCard"),
    COMPOUND_STRING("ObjectEventInteractionGetBerryTreeData"),
    COMPOUND_STRING("ObjectEventInteractionGetBerryName"),
    COMPOUND_STRING("ObjectEventInteractionGetBerryCountString"),
    COMPOUND_STRING("Bag_ChooseBerry"),
    COMPOUND_STRING("ObjectEventInteractionPlantBerryTree"),
    COMPOUND_STRING("ObjectEventInteractionPickBerryTree"),
    COMPOUND_STRING("ObjectEventInteractionRemoveBerryTree"),
    COMPOUND_STRING("ObjectEventInteractionWaterBerryTree"),
    COMPOUND_STRING("PlayerHasBerries"),
    COMPOUND_STRING("IsEnigmaBerryValid"),
    COMPOUND_STRING("GetTrainerBattleMode"),
    COMPOUND_STRING("ShowTrainerIntroSpeech"),
    COMPOUND_STRING("ShowTrainerCantBattleSpeech"),
    COMPOUND_STRING("GetTrainerFlag"),
    COMPOUND_STRING("DoTrainerApproach"),
    COMPOUND_STRING("PlayTrainerEncounterMusic"),
    COMPOUND_STRING("ShouldTryRematchBattle"),
    COMPOUND_STRING("IsTrainerReadyForRematch"),
    COMPOUND_STRING("BattleSetup_StartRematchBattle"),
    COMPOUND_STRING("ShowPokemonStorageSystemPC"),
    COMPOUND_STRING("HasEnoughMonsForDoubleBattle"),
    COMPOUND_STRING("TurnOffTVScreen"),
    COMPOUND_STRING("DoTVShow"),
    COMPOUND_STRING("DoPokeNews"),
    COMPOUND_STRING("GetRandomActiveShowIdx"),
    COMPOUND_STRING("GetSelectedTVShow"),
    COMPOUND_STRING("InterviewBefore"),
    COMPOUND_STRING("InterviewAfter"),
    COMPOUND_STRING("IsLeadMonNicknamedOrNotEnglish"),
    COMPOUND_STRING("SetContestCategoryStringVarForInterview"),
    COMPOUND_STRING("GetNextActiveShowIfMassOutbreak"),
    COMPOUND_STRING("IsTVShowAlreadyInQueue"),
    COMPOUND_STRING("CheckForPlayersHouseNews"),
    COMPOUND_STRING("GetMomOrDadStringForTVMessage"),
    COMPOUND_STRING("ResetTVShowState"),
    COMPOUND_STRING("GetContestWinnerId"),
    COMPOUND_STRING("GetContestPlayerId"),
    COMPOUND_STRING("GetNpcContestantLocalId"),
    COMPOUND_STRING("BufferContestWinnerTrainerName"),
    COMPOUND_STRING("BufferContestWinnerMonName"),
    COMPOUND_STRING("BufferContestTrainerAndMonNames"),
    COMPOUND_STRING("GetContestMonConditionRanking"),
    COMPOUND_STRING("SetContestTrainerGfxIds"),
    COMPOUND_STRING("TryEnterContestMon"),
    COMPOUND_STRING("GetContestantNamesAtRank"),
    COMPOUND_STRING("SetLinkContestPlayerGfx"),
    COMPOUND_STRING("GetContestMonCondition"),
    COMPOUND_STRING("HasMonWonThisContestBefore"),
    COMPOUND_STRING("GiveMonContestRibbon"),
    COMPOUND_STRING("IsContestDebugActive"),
    COMPOUND_STRING("GiveMonArtistRibbon"),
    COMPOUND_STRING("TryContestGModeLinkup"),
    COMPOUND_STRING("SaveGame"),
    COMPOUND_STRING("DoWateringBerryTreeAnim"),
    COMPOUND_STRING("ShowEasyChatScreen"),
    COMPOUND_STRING("ShowEasyChatProfile"),
    COMPOUND_STRING("Script_GetCurrentMauvilleMan"),
    COMPOUND_STRING("HasBardSongBeenChanged"),
    COMPOUND_STRING("SaveBardSongLyrics"),
    COMPOUND_STRING("HasHipsterTaughtWord"),
    COMPOUND_STRING("SetHipsterTaughtWord"),
    COMPOUND_STRING("HipsterTryTeachWord"),
    COMPOUND_STRING("PlayBardSong"),
    COMPOUND_STRING("SetMauvilleOldManObjEventGfx"),
    COMPOUND_STRING("GenerateGiddyLine"),
    COMPOUND_STRING("GiddyShouldTellAnotherTale"),
    COMPOUND_STRING("StorytellerGetFreeStorySlot"),
    COMPOUND_STRING("Script_StorytellerDisplayStory"),
    COMPOUND_STRING("StorytellerStoryListMenu"),
    COMPOUND_STRING("StorytellerUpdateStat"),
    COMPOUND_STRING("Script_StorytellerInitializeRandomStat"),
    COMPOUND_STRING("HasStorytellerAlreadyRecorded"),
    COMPOUND_STRING("TraderMenuGetDecoration"),
    COMPOUND_STRING("GetTraderTradedFlag"),
    COMPOUND_STRING("DoesPlayerHaveNoDecorations"),
    COMPOUND_STRING("IsDecorationCategoryFull"),
    COMPOUND_STRING("TraderShowDecorationMenu"),
    COMPOUND_STRING("TraderDoDecorationTrade"),
    COMPOUND_STRING("GetSeedotSizeRecordInfo"),
    COMPOUND_STRING("CompareSeedotSize"),
    COMPOUND_STRING("GetLotadSizeRecordInfo"),
    COMPOUND_STRING("CompareLotadSize"),
    COMPOUND_STRING("TryPutNameRaterShowOnTheAir"),
    COMPOUND_STRING("BufferMonNickname"),
    COMPOUND_STRING("IsMonOTIDNotPlayers"),
    COMPOUND_STRING("BufferTrendyPhraseString"),
    COMPOUND_STRING("IsTrendyPhraseBoring"),
    COMPOUND_STRING("BufferDeepLinkPhrase"),
    COMPOUND_STRING("GetDewfordHallPaintingNameIndex"),
    COMPOUND_STRING("SwapRegisteredBike"),
    COMPOUND_STRING("CalculatePlayerPartyCount"),
    COMPOUND_STRING("CountPartyNonEggMons"),
    COMPOUND_STRING("CountPartyAliveNonEggMons_IgnoreVar0x8004Slot"),
    COMPOUND_STRING("ShouldReadyContestArtist"),
    COMPOUND_STRING("SaveMuseumContestPainting"),
    COMPOUND_STRING("DoesContestCategoryHaveMuseumPainting"),
    COMPOUND_STRING("CountPlayerMuseumPaintings"),
    COMPOUND_STRING("ShowContestPainting"),
    COMPOUND_STRING("MauvilleGymSetDefaultBarriers"),
    COMPOUND_STRING("MauvilleGymPressSwitch"),
    COMPOUND_STRING("ShowFieldMessageStringVar4"),
    COMPOUND_STRING("DrawWholeMapView"),
    COMPOUND_STRING("StorePlayerCoordsInVars"),
    COMPOUND_STRING("MauvilleGymDeactivatePuzzle"),
    COMPOUND_STRING("PetalburgGymSlideOpenRoomDoors"),
    COMPOUND_STRING("PetalburgGymUnlockRoomDoors"),
    COMPOUND_STRING("GetPlayerTrainerIdOnesDigit"),
    COMPOUND_STRING("GetPlayerBigGuyGirlString"),
    COMPOUND_STRING("GetRivalSonDaughterString"),
    COMPOUND_STRING("SetHiddenItemFlag"),
    COMPOUND_STRING("CableCarWarp"),
    COMPOUND_STRING("CableCar"),
    COMPOUND_STRING("Overworld_PlaySpecialMapMusic"),
    COMPOUND_STRING("StartWallClock"),
    COMPOUND_STRING("Special_ViewWallClock"),
    COMPOUND_STRING("ChooseStarter"),
    COMPOUND_STRING("StartWallyTutorialBattle"),
    COMPOUND_STRING("ChangePokemonNickname"),
    COMPOUND_STRING("ChoosePartyMon"),
    COMPOUND_STRING("GetFirstFreePokeblockSlot"),
    COMPOUND_STRING("DoBerryBlending"),
    COMPOUND_STRING("PlayRoulette"),
    COMPOUND_STRING("IsFanClubMemberFanOfPlayer"),
    COMPOUND_STRING("GetNumFansOfPlayerInTrainerFanClub"),
    COMPOUND_STRING("BufferFanClubTrainerName"),
    COMPOUND_STRING("TryLoseFansFromPlayTimeAfterLinkBattle"),
    COMPOUND_STRING("TryLoseFansFromPlayTime"),
    COMPOUND_STRING("SetPlayerGotFirstFans"),
    COMPOUND_STRING("UpdateTrainerFanClubGameClear"),
    COMPOUND_STRING("Script_TryGainNewFanFromCounter"),
    COMPOUND_STRING("RockSmashWildEncounter"),
    COMPOUND_STRING("GabbyAndTyGetBattleNum"),
    COMPOUND_STRING("GabbyAndTyAfterInterview"),
    COMPOUND_STRING("GabbyAndTyBeforeInterview"),
    COMPOUND_STRING("DoTVShowInSearchOfTrainers"),
    COMPOUND_STRING("IsGabbyAndTyShowOnTheAir"),
    COMPOUND_STRING("GabbyAndTyGetLastQuote"),
    COMPOUND_STRING("GabbyAndTyGetLastBattleTrivia"),
    COMPOUND_STRING("GetGabbyAndTyLocalIds"),
    COMPOUND_STRING("GetBattleOutcome"),
    COMPOUND_STRING("GetDaycareMonNicknames"),
    COMPOUND_STRING("GetDaycareState"),
    COMPOUND_STRING("RejectEggFromDayCare"),
    COMPOUND_STRING("GiveEggFromDaycare"),
    COMPOUND_STRING("SetDaycareCompatibilityString"),
    COMPOUND_STRING("GetSelectedMonNicknameAndSpecies"),
    COMPOUND_STRING("StoreSelectedPokemonInDaycare"),
    COMPOUND_STRING("ChooseSendDaycareMon"),
    COMPOUND_STRING("ShowDaycareLevelMenu"),
    COMPOUND_STRING("GetNumLevelsGainedFromDaycare"),
    COMPOUND_STRING("GetDaycareCost"),
    COMPOUND_STRING("TakePokemonFromDaycare"),
    COMPOUND_STRING("ScriptHatchMon"),
    COMPOUND_STRING("EggHatch"),
    COMPOUND_STRING("CheckDaycareMonReceivedMail"),
    COMPOUND_STRING("ShowLinkBattleRecords"),
    COMPOUND_STRING("IsEnoughForCostInVar0x8005"),
    COMPOUND_STRING("SubtractMoneyFromVar0x8005"),
    COMPOUND_STRING("TryFieldPoisonWhiteOut"),
    COMPOUND_STRING("SetCB2WhiteOut"),
    COMPOUND_STRING("RotatingGate_InitPuzzle"),
    COMPOUND_STRING("RotatingGate_InitPuzzleAndGraphics"),
    COMPOUND_STRING("SetSSTidalFlag"),
    COMPOUND_STRING("ResetSSTidalFlag"),
    COMPOUND_STRING("EnterSafariMode"),
    COMPOUND_STRING("ExitSafariMode"),
    COMPOUND_STRING("GetPokeblockFeederInFront"),
    COMPOUND_STRING("OpenPokeblockCaseOnFeeder"),
    COMPOUND_STRING("IsMirageIslandPresent"),
    COMPOUND_STRING("UpdateShoalTideFlag"),
    COMPOUND_STRING("InitBirchState"),
    COMPOUND_STRING("ScriptGetPokedexInfo"),
    COMPOUND_STRING("ShowPokedexRatingMessage"),
    COMPOUND_STRING("DoPCTurnOnEffect"),
    COMPOUND_STRING("DoPCTurnOffEffect"),
    COMPOUND_STRING("SetDeptStoreFloor"),
    COMPOUND_STRING("DoLotteryCornerComputerEffect"),
    COMPOUND_STRING("EndLotteryCornerComputerEffect"),
    COMPOUND_STRING("ChooseMonForMoveRelearner"),
    COMPOUND_STRING("MoveDeleterChooseMoveToForget"),
    COMPOUND_STRING("MoveDeleterForgetMove"),
    COMPOUND_STRING("BufferMoveDeleterNicknameAndMove"),
    COMPOUND_STRING("GetNumMovesSelectedMonHas"),
    COMPOUND_STRING("TeachMoveRelearnerMove"),
    COMPOUND_STRING("GetRecordedCyclingRoadResults"),
    COMPOUND_STRING("Special_BeginCyclingRoadChallenge"),
    COMPOUND_STRING("GetPlayerAvatarBike"),
    COMPOUND_STRING("FinishCyclingRoadChallenge"),
    COMPOUND_STRING("UpdateCyclingRoadState"),
    COMPOUND_STRING("GetLeadMonFriendshipScore"),
    COMPOUND_STRING("CallFrontierUtilFunc"),
    COMPOUND_STRING("CallBattleTowerFunc"),
    COMPOUND_STRING("CallBattleDomeFunction"),
    COMPOUND_STRING("CallBattlePalaceFunction"),
    COMPOUND_STRING("CopyEReaderTrainerGreeting"),
    COMPOUND_STRING("DoSpecialTrainerBattle"),
    COMPOUND_STRING("CallBattleArenaFunction"),
    COMPOUND_STRING("CallBattleFactoryFunction"),
    COMPOUND_STRING("CallBattlePikeFunction"),
    COMPOUND_STRING("CallBattlePyramidFunction"),
    COMPOUND_STRING("StopMapMusic"),
    COMPOUND_STRING("CallVerdanturfTentFunction"),
    COMPOUND_STRING("CallFallarborTentFunction"),
    COMPOUND_STRING("CallSlateportTentFunction"),
    COMPOUND_STRING("ChoosePartyForBattleFrontier"),
    COMPOUND_STRING("ValidateEReaderTrainer"),
    COMPOUND_STRING("GetBattleTowerSinglesStreak"),
    COMPOUND_STRING("ReducePlayerPartyToSelectedMons"),
    COMPOUND_STRING("BedroomPC"),
    COMPOUND_STRING("PlayerPC"),
    COMPOUND_STRING("FieldShowRegionMap"),
    COMPOUND_STRING("GetInGameTradeSpeciesInfo"),
    COMPOUND_STRING("CreateInGameTradePokemon"),
    COMPOUND_STRING("DoInGameTradeScene"),
    COMPOUND_STRING("GetTradeSpecies"),
    COMPOUND_STRING("GetWeekCount"),
    COMPOUND_STRING("RetrieveLotteryNumber"),
    COMPOUND_STRING("PickLotteryCornerTicket"),
    COMPOUND_STRING("ShowBerryBlenderRecordWindow"),
    COMPOUND_STRING("ResetTrickHouseNuggetFlag"),
    COMPOUND_STRING("SetTrickHouseNuggetFlag"),
    COMPOUND_STRING("ScriptMenu_CreatePCMultichoice"),
    COMPOUND_STRING("AccessHallOfFamePC"),
    COMPOUND_STRING("Special_ShowDiploma"),
    COMPOUND_STRING("CheckLeadMonCool"),
    COMPOUND_STRING("CheckLeadMonBeauty"),
    COMPOUND_STRING("CheckLeadMonCute"),
    COMPOUND_STRING("CheckLeadMonSmart"),
    COMPOUND_STRING("CheckLeadMonTough"),
    COMPOUND_STRING("LookThroughPorthole"),
    COMPOUND_STRING("DoSoftReset"),
    COMPOUND_STRING("GameClear"),
    COMPOUND_STRING("MoveElevator"),
    COMPOUND_STRING("ShowGlassWorkshopMenu"),
    COMPOUND_STRING("SpawnCameraObject"),
    COMPOUND_STRING("RemoveCameraObject"),
    COMPOUND_STRING("GetPokeblockNameByMonNature"),
    COMPOUND_STRING("GetSecretBaseNearbyMapName"),
    COMPOUND_STRING("CheckRelicanthWailord"),
    COMPOUND_STRING("ShouldDoBrailleRegirockEffectOld"),
    COMPOUND_STRING("DoOrbEffect"),
    COMPOUND_STRING("FadeOutOrbEffect"),
    COMPOUND_STRING("WaitWeather"),
    COMPOUND_STRING("BufferEReaderTrainerName"),
    COMPOUND_STRING("GetSlotMachineId"),
    COMPOUND_STRING("GetPlayerFacingDirection"),
    COMPOUND_STRING("FoundAbandonedShipRoom1Key"),
    COMPOUND_STRING("FoundAbandonedShipRoom2Key"),
    COMPOUND_STRING("FoundAbandonedShipRoom4Key"),
    COMPOUND_STRING("FoundAbandonedShipRoom6Key"),
    COMPOUND_STRING("LeadMonHasEffortRibbon"),
    COMPOUND_STRING("GiveLeadMonEffortRibbon"),
    COMPOUND_STRING("Special_AreLeadMonEVsMaxedOut"),
    COMPOUND_STRING("Script_FacePlayer"),
    COMPOUND_STRING("Script_ClearHeldMovement"),
    COMPOUND_STRING("InitRoamer"),
    COMPOUND_STRING("TryUpdateRusturfTunnelState"),
    COMPOUND_STRING("IsGrassTypeInParty"),
    COMPOUND_STRING("DoContestHallWarp"),
    COMPOUND_STRING("LoadWallyZigzagoon"),
    COMPOUND_STRING("IsStarterInParty"),
    COMPOUND_STRING("CopyCurSecretBaseOwnerName_StrVar1"),
    COMPOUND_STRING("ScriptCheckFreePokemonStorageSpace"),
    COMPOUND_STRING("DoSealedChamberShakingEffect_Long"),
    COMPOUND_STRING("ShowDeptStoreElevatorFloorSelect"),
    COMPOUND_STRING("InteractWithShieldOrTVDecoration"),
    COMPOUND_STRING("IsPokerusInParty"),
    COMPOUND_STRING("SetSootopolisGymCrackedIceMetatiles"),
    COMPOUND_STRING("ShakeCamera"),
    COMPOUND_STRING("StartGroudonKyogreBattle"),
    COMPOUND_STRING("BattleSetup_StartLegendaryBattle"),
    COMPOUND_STRING("StartRegiBattle"),
    COMPOUND_STRING("SetTrainerFacingDirection"),
    COMPOUND_STRING("DoSealedChamberShakingEffect_Short"),
    COMPOUND_STRING("FoundBlackGlasses"),
    COMPOUND_STRING("StartDroughtWeatherBlend"),
    COMPOUND_STRING("DoDiveWarp"),
    COMPOUND_STRING("DoFallWarp"),
    COMPOUND_STRING("ShowContestEntryMonPic"),
    COMPOUND_STRING("HideContestEntryMonPic"),
    COMPOUND_STRING("SetEReaderTrainerGfxId"),
    COMPOUND_STRING("BattleSetup_StartLatiBattle"),
    COMPOUND_STRING("SetRoute119Weather"),
    COMPOUND_STRING("SetRoute123Weather"),
    COMPOUND_STRING("GetContestMultiplayerId"),
    COMPOUND_STRING("ScriptGetPartyMonSpecies"),
    COMPOUND_STRING("IsSelectedMonEgg"),
    COMPOUND_STRING("TryInitBattleTowerAwardManObjectEvent"),
    COMPOUND_STRING("MoveOutOfSecretBaseFromOutside"),
    COMPOUND_STRING("LoadPlayerBag"),
    COMPOUND_STRING("Script_FadeOutMapMusic"),
    COMPOUND_STRING("SetPacifidlogTMReceivedDay"),
    COMPOUND_STRING("GetDaysUntilPacifidlogTMAvailable"),
    COMPOUND_STRING("HasAllHoennMons"),
    COMPOUND_STRING("MonOTNameNotPlayer"),
    COMPOUND_STRING("BufferLottoTicketNumber"),
    COMPOUND_STRING("TryHideBattleTowerReporter"),
    COMPOUND_STRING("DoesPartyHaveEnigmaBerry"),
    COMPOUND_STRING("GenerateContestRand"),
    COMPOUND_STRING("SetChampionSaveWarp"),
    COMPOUND_STRING("TryPutTreasureInvestigatorsOnAir"),
    COMPOUND_STRING("TryPutLotteryWinnerReportOnAir"),
    COMPOUND_STRING("TryPutTrainerFanClubOnAir"),
    COMPOUND_STRING("ShouldHideFanClubInterviewer"),
    COMPOUND_STRING("ShowGlassWorkshopMenu"),
    COMPOUND_STRING("PutFanClubSpecialOnTheAir"),
    COMPOUND_STRING("IncrementDailyPlantedBerries"),
    COMPOUND_STRING("IncrementDailyPickedBerries"),
    COMPOUND_STRING("InitSecretBaseVars"),
    COMPOUND_STRING("CheckInteractedWithFriendsSandOrnament"),
    COMPOUND_STRING("DeclinedSecretBaseBattle"),
    COMPOUND_STRING("DrewSecretBaseBattle"),
    COMPOUND_STRING("WonSecretBaseBattle"),
    COMPOUND_STRING("LostSecretBaseBattle"),
    COMPOUND_STRING("CheckInteractedWithFriendsDollDecor"),
    COMPOUND_STRING("CheckInteractedWithFriendsCushionDecor"),
    COMPOUND_STRING("CheckInteractedWithFriendsFurnitureBottom"),
    COMPOUND_STRING("CheckInteractedWithFriendsFurnitureMiddle"),
    COMPOUND_STRING("CheckInteractedWithFriendsFurnitureTop"),
    COMPOUND_STRING("CheckInteractedWithFriendsPosterDecor"),
    COMPOUND_STRING("SetLilycoveLadyGfx"),
    COMPOUND_STRING("Script_GetLilycoveLadyId"),
    COMPOUND_STRING("GetFavorLadyState"),
    COMPOUND_STRING("BufferFavorLadyRequest"),
    COMPOUND_STRING("HasAnotherPlayerGivenFavorLadyItem"),
    COMPOUND_STRING("BufferFavorLadyItemName"),
    COMPOUND_STRING("BufferFavorLadyPlayerName"),
    COMPOUND_STRING("DidFavorLadyLikeItem"),
    COMPOUND_STRING("Script_FavorLadyOpenBagMenu"),
    COMPOUND_STRING("Script_DoesFavorLadyLikeItem"),
    COMPOUND_STRING("IsFavorLadyThresholdMet"),
    COMPOUND_STRING("FavorLadyGetPrize"),
    COMPOUND_STRING("SetFavorLadyState_Complete"),
    COMPOUND_STRING("GetQuizLadyState"),
    COMPOUND_STRING("GetQuizAuthor"),
    COMPOUND_STRING("IsQuizLadyWaitingForChallenger"),
    COMPOUND_STRING("QuizLadyShowQuizQuestion"),
    COMPOUND_STRING("QuizLadyGetPlayerAnswer"),
    COMPOUND_STRING("IsQuizAnswerCorrect"),
    COMPOUND_STRING("BufferQuizPrizeItem"),
    COMPOUND_STRING("SetQuizLadyState_Complete"),
    COMPOUND_STRING("BufferQuizAuthorNameAndCheckIfLady"),
    COMPOUND_STRING("SetQuizLadyState_GivePrize"),
    COMPOUND_STRING("ClearQuizLadyPlayerAnswer"),
    COMPOUND_STRING("Script_QuizLadyOpenBagMenu"),
    COMPOUND_STRING("ClearQuizLadyQuestionAndAnswer"),
    COMPOUND_STRING("QuizLadySetCustomQuestion"),
    COMPOUND_STRING("QuizLadyTakePrizeForCustomQuiz"),
    COMPOUND_STRING("GetMysteryGiftCardStat"),
    COMPOUND_STRING("QuizLadyRecordCustomQuizData"),
    COMPOUND_STRING("QuizLadySetWaitingForChallenger"),
    COMPOUND_STRING("BufferQuizCorrectAnswer"),
    COMPOUND_STRING("BufferQuizPrizeName"),
    COMPOUND_STRING("QuizLadyPickNewQuestion"),
    COMPOUND_STRING("ShouldContestLadyShowGoOnAir"),
    COMPOUND_STRING("HasPlayerGivenContestLadyPokeblock"),
    COMPOUND_STRING("Script_BufferContestLadyCategoryAndMonName"),
    COMPOUND_STRING("OpenPokeblockCaseForContestLady"),
    COMPOUND_STRING("SetContestLadyGivenPokeblock"),
    COMPOUND_STRING("GetContestLadyMonSpecies"),
    COMPOUND_STRING("GetContestLadyCategory"),
    COMPOUND_STRING("PutLilycoveContestLadyShowOnTheAir"),
    COMPOUND_STRING("CloseBattlePikeCurtain"),
    COMPOUND_STRING("CallApprenticeFunction"),
    COMPOUND_STRING("ShouldTryGetTrainerScript"),
    COMPOUND_STRING("ShowMapNamePopup"),
    COMPOUND_STRING("ShowMapNamePopup"),
    COMPOUND_STRING("DoMirageTowerCeilingCrumble"),
    COMPOUND_STRING("SetMirageTowerVisibility"),
    COMPOUND_STRING("StartPlayerDescendMirageTower"),
    COMPOUND_STRING("BufferTMHMMoveName"),
    COMPOUND_STRING("IsWirelessAdapterConnected"),
    COMPOUND_STRING("TryBecomeLinkLeader"),
    COMPOUND_STRING("TryJoinLinkGroup"),
    COMPOUND_STRING("RunUnionRoom"),
    COMPOUND_STRING("ShowWirelessCommunicationScreen"),
    COMPOUND_STRING("InitUnionRoom"),
    COMPOUND_STRING("BufferUnionRoomPlayerName"),
    COMPOUND_STRING("WonderNews_GetRewardInfo"),
    COMPOUND_STRING("ChooseMonForWirelessMinigame"),
    COMPOUND_STRING("Script_ResetUnionRoomTrade"),
    COMPOUND_STRING("IsBadEggInParty"),
    COMPOUND_STRING("ValidateSavedWonderCard"),
    COMPOUND_STRING("HasAtLeastOneBerry"),
    COMPOUND_STRING("IsPokemonJumpSpeciesInParty"),
    COMPOUND_STRING("ShowPokemonJumpRecords"),
    COMPOUND_STRING("IsDodrioInParty"),
    COMPOUND_STRING("ShowDodrioBerryPickingRecords"),
    COMPOUND_STRING("OffsetCameraForBattle"),
    COMPOUND_STRING("GetDeptStoreDefaultFloorChoice"),
    COMPOUND_STRING("BufferVarsForIVRater"),
    COMPOUND_STRING("LinkContestWaitForConnection"),
    COMPOUND_STRING("GetWirelessCommType"),
    COMPOUND_STRING("LinkContestTryShowWirelessIndicator"),
    COMPOUND_STRING("LinkContestTryHideWirelessIndicator"),
    COMPOUND_STRING("IsWirelessContest"),
    COMPOUND_STRING("ShowRankingHallRecordsWindow"),
    COMPOUND_STRING("ScrollRankingHallRecordsWindow"),
    COMPOUND_STRING("ShowFrontierManiacMessage"),
    COMPOUND_STRING("IsContestWithRSPlayer"),
    COMPOUND_STRING("ClearLinkContestFlags"),
    COMPOUND_STRING("TryContestEModeLinkup"),
    COMPOUND_STRING("ShowScrollableMultichoice"),
    COMPOUND_STRING("ScrollableMultichoice_TryReturnToList"),
    COMPOUND_STRING("BufferBattleTowerElevatorFloors"),
    COMPOUND_STRING("TryStoreHeldItemsInPyramidBag"),
    COMPOUND_STRING("ChooseItemsToTossFromPyramidBag"),
    COMPOUND_STRING("DoBattlePyramidMonsHaveHeldItem"),
    COMPOUND_STRING("BattlePyramidChooseMonHeldItems"),
    COMPOUND_STRING("SetBattleTowerLinkPlayerGfx"),
    COMPOUND_STRING("ShowNatureGirlMessage"),
    COMPOUND_STRING("ShowBattlePointsWindow"),
    COMPOUND_STRING("UpdateBattlePointsWindow"),
    COMPOUND_STRING("CloseBattlePointsWindow"),
    COMPOUND_STRING("GiveFrontierBattlePoints"),
    COMPOUND_STRING("TakeFrontierBattlePoints"),
    COMPOUND_STRING("GetFrontierBattlePoints"),
    COMPOUND_STRING("ShowFrontierExchangeCornerItemIconWindow"),
    COMPOUND_STRING("CloseFrontierExchangeCornerItemIconWindow"),
    COMPOUND_STRING("DisplayBerryPowderVendorMenu"),
    COMPOUND_STRING("RemoveBerryPowderVendorMenu"),
    COMPOUND_STRING("HasEnoughBerryPowder"),
    COMPOUND_STRING("TakeBerryPowder"),
    COMPOUND_STRING("PrintPlayerBerryPowderAmount"),
    COMPOUND_STRING("ShowFrontierGamblerLookingMessage"),
    COMPOUND_STRING("ShowFrontierGamblerGoMessage"),
    COMPOUND_STRING("Script_DoRayquazaScene"),
    COMPOUND_STRING("OpenPokenavForTutorial"),
    COMPOUND_STRING("ScriptMenu_CreateStartMenuForPokenavTutorial"),
    COMPOUND_STRING("CountPlayerTrainerStars"),
    COMPOUND_STRING("BufferBattleFrontierTutorMoveName"),
    COMPOUND_STRING("CloseBattleFrontierTutorWindow"),
    COMPOUND_STRING("ScrollableMultichoice_RedrawPersistentMenu"),
    COMPOUND_STRING("ChooseMonForMoveTutor"),
    COMPOUND_STRING("ScrollableMultichoice_ClosePersistentMenu"),
    COMPOUND_STRING("DoDeoxysRockInteraction"),
    COMPOUND_STRING("SetDeoxysRockPalette"),
    COMPOUND_STRING("CreateEnemyEventMon"),
    COMPOUND_STRING("StartMirageTowerDisintegration"),
    COMPOUND_STRING("StartMirageTowerShake"),
    COMPOUND_STRING("StartMirageTowerFossilFallAndSink"),
    COMPOUND_STRING("ChangeBoxPokemonNickname"),
    COMPOUND_STRING("GetPCBoxToSendMon"),
    COMPOUND_STRING("ShouldShowBoxWasFullMessage"),
    COMPOUND_STRING("SetMatchCallRegisteredFlag"),
    COMPOUND_STRING("DoDomeConfetti"),
    COMPOUND_STRING("CreateAbnormalWeatherEvent"),
    COMPOUND_STRING("GetAbnormalWeatherMapNameAndType"),
    COMPOUND_STRING("GetMartEmployeeObjectEventId"),
    COMPOUND_STRING("SaveForBattleTowerLink"),
    COMPOUND_STRING("Unused_SetWeatherSunny"),
    COMPOUND_STRING("SetUnlockedPokedexFlags"),
    COMPOUND_STRING("IsTrainerRegistered"),
    COMPOUND_STRING("ShouldDoBrailleRegicePuzzle"),
    COMPOUND_STRING("EnableNationalPokedex"),
    COMPOUND_STRING("ScriptMenu_CreateLilycoveSSTidalMultichoice"),
    COMPOUND_STRING("GetLilycoveSSTidalSelection"),
    COMPOUND_STRING("TurnOnTVScreen"),
    COMPOUND_STRING("SetMewAboveGrass"),
    COMPOUND_STRING("ShouldDistributeEonTicket"),
    COMPOUND_STRING("LinkRetireStatusWithBattleTowerPartner"),
    COMPOUND_STRING("BattleTowerReconnectLink"),
    COMPOUND_STRING("CallTrainerHillFunction"),
    COMPOUND_STRING("Script_DoRayquazaScene"),
    COMPOUND_STRING("LoopWingFlapSE"),
    COMPOUND_STRING("DestroyMewEmergingGrassSprite"),
    COMPOUND_STRING("ShowBerryCrushRankings"),
    COMPOUND_STRING("TryBufferWaldaPhrase"),
    COMPOUND_STRING("DoWaldaNamingScreen"),
    COMPOUND_STRING("TryGetWallpaperWithWaldaPhrase"),
    COMPOUND_STRING("PlayerNotAtTrainerHillEntrance"),
    COMPOUND_STRING("GetBattlePyramidHint"),
    COMPOUND_STRING("LoadLinkContestPlayerPalettes"),
    COMPOUND_STRING("ShowTrainerHillRecords"),
    COMPOUND_STRING("PlayerFaceTrainerAfterBattle"),
    COMPOUND_STRING("ResetHealLocationFromDewford"),
    COMPOUND_STRING("IsLastMonThatKnowsSurf"),
    COMPOUND_STRING("CountPartyAliveNonEggMons"),
    COMPOUND_STRING("TryPrepareSecondApproachingTrainer"),
    COMPOUND_STRING("RemoveRecordsWindow"),
    COMPOUND_STRING("CloseDeptStoreElevatorWindow"),
    COMPOUND_STRING("TrySetBattleTowerLinkType"),
    COMPOUND_STRING("TrySpecialOverworldEvo"),
    COMPOUND_STRING("GetNumberSprayStrength"),
    COMPOUND_STRING("GetSprayId"),
    COMPOUND_STRING("GetLastUsedSprayType"),
    COMPOUND_STRING("TrySkyBattle"),
    COMPOUND_STRING("VsSeekerResetObjectMovementAfterChargeComplete"),
    COMPOUND_STRING("VsSeekerFreezeObjectsAfterChargeComplete"),
    COMPOUND_STRING("PlayerHasMulch"),
    COMPOUND_STRING("Bag_ChooseMulch"),
    COMPOUND_STRING("ObjectEventInteractionApplyMulch"),
    COMPOUND_STRING("ObjectEventInteractionPullBerryWeed"),
    COMPOUND_STRING("ObjectEventInteractionClearBerryPests"),
    COMPOUND_STRING("ObjectEventInteractionBerryHasWeed"),
    COMPOUND_STRING("ObjectEventInteractionBerryHasPests"),
    COMPOUND_STRING("CanWaterBerryPlot"),
    COMPOUND_STRING("Script_GetChosenMonOffensiveEVs"),
    COMPOUND_STRING("Script_GetChosenMonDefensiveEVs"),
    COMPOUND_STRING("Script_GetChosenMonOffensiveIVs"),
    COMPOUND_STRING("Script_GetChosenMonDefensiveIVs"),
    COMPOUND_STRING("UseBlankMessageToCancelPokemonPic"),
    COMPOUND_STRING("EnterCode"),
    COMPOUND_STRING("GetCodeFeedback"),
    COMPOUND_STRING("SetHiddenNature")
};

const u8 *const gMapScriptTypeStrings[] = 
{
    [0] = COMPOUND_STRING("NO_MAP_SCRIPT"),
    [MAP_SCRIPT_ON_LOAD] = COMPOUND_STRING("MAP_SCRIPT_ON_LOAD"),
    [MAP_SCRIPT_ON_FRAME_TABLE] = COMPOUND_STRING("MAP_SCRIPT_ON_FRAME_TABLE"),
    [MAP_SCRIPT_ON_TRANSITION] = COMPOUND_STRING("MAP_SCRIPT_ON_TRANSITION"),
    [MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE] = COMPOUND_STRING("MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE"),
    [MAP_SCRIPT_ON_RESUME] = COMPOUND_STRING("MAP_SCRIPT_ON_RESUME"),
    [MAP_SCRIPT_ON_DIVE_WARP] = COMPOUND_STRING("MAP_SCRIPT_ON_DIVE_WARP"),
    [MAP_SCRIPT_ON_RETURN_TO_FIELD] = COMPOUND_STRING("MAP_SCRIPT_ON_RETURN_TO_FIELD"),
};

void ActivateScriptDebugger(void)
{
    gActiveScriptDebugger = TRUE;
}

void DeactivateScriptDebugger(void)
{
    gActiveScriptDebugger = FALSE;
}

#endif