# 1 "data/maps/Emberglide/scripts.pory"

# 2 "data/maps/Emberglide/scripts.pory"
Emberglide_MapScripts::
# 3 "data/maps/Emberglide/scripts.pory"
	.byte 0

Emberglide_EventScript_Weepinbell::
# 7 "data/maps/Emberglide/scripts.pory"
	speakername Emberglide_EventScript_Weepinbell_Text_0
# 8 "data/maps/Emberglide/scripts.pory"
	msgbox Emberglide_EventScript_Weepinbell_Text_1, MSGBOX_NPC
# 17 "data/maps/Emberglide/scripts.pory"
	release
	end


Emberglide_EventScript_Ledyba::
# 23 "data/maps/Emberglide/scripts.pory"
	speakername Emberglide_EventScript_Ledyba_Text_0
# 24 "data/maps/Emberglide/scripts.pory"
	msgbox Emberglide_EventScript_Ledyba_Text_1, MSGBOX_NPC
	end


Emberglide_EventScript_Magby::
# 37 "data/maps/Emberglide/scripts.pory"
	speakername Emberglide_EventScript_Magby_Text_0
# 38 "data/maps/Emberglide/scripts.pory"
	msgbox Emberglide_EventScript_Magby_Text_1, MSGBOX_NPC
	end


Emberglide_EventScript_Weepinbell_Text_0:
# 7 "data/maps/Emberglide/scripts.pory"
	.string "Weepinbell$"

Emberglide_EventScript_Weepinbell_Text_1:
# 9 "data/maps/Emberglide/scripts.pory"
	.string "Welcome to Emberglide!\p"
	.string "We're a quaint and historic town with a\n"
	.string "rich history and-…\p"
	.string "… … …\p"
	.string "You're looking for Pyroden.\n"
	.string "Of course.\p"
	.string "Left on Route 2, and then up.\n"
	.string "Sigh…$"

Emberglide_EventScript_Ledyba_Text_0:
# 23 "data/maps/Emberglide/scripts.pory"
	.string "Ledyba$"

Emberglide_EventScript_Ledyba_Text_1:
# 25 "data/maps/Emberglide/scripts.pory"
	.string "Uhm, uhm!\n"
	.string "I'm worried for my friend!\p"
	.string "We used to hang out lots, but it's been\n"
	.string "a while since I've seen her.\p"
	.string "She lives in Driftshore, but the way\n"
	.string "through Dominion City is dangerous now!\p"
	.string "If you see her, could you check up on\n"
	.string "her?\p"
	.string "THIS IS A QUEST SETUP. THE QUEST IS NOT\n"
	.string "IMPLEMENTED YET.$"

Emberglide_EventScript_Magby_Text_0:
# 37 "data/maps/Emberglide/scripts.pory"
	.string "Magby$"

Emberglide_EventScript_Magby_Text_1:
# 39 "data/maps/Emberglide/scripts.pory"
	.string "There's not many humans around here,\n"
	.string "usually.\l"
	.string "Never really liked them, anyway.\p"
	.string "They stink. And are rude. And ugly.\n"
	.string "I'm sure you agree.$"
